(function() {
var _UDS_CONST_LOCALE = 'fi';
var _UDS_CONST_SHORT_DATE_PATTERN = 'DMY'; 
var _UDS_MSG_SEARCHER_IMAGE = ('Kuva'); 
var _UDS_MSG_SEARCHER_WEB = ('Web'); 
var _UDS_MSG_SEARCHER_BLOG = ('Blogi'); 
var _UDS_MSG_SEARCHER_VIDEO = ('Video'); 
var _UDS_MSG_SEARCHER_LOCAL = ('Paikalliset'); 
var _UDS_MSG_SEARCHCONTROL_SAVE = ('tallenna'); 
var _UDS_MSG_SEARCHCONTROL_KEEP = ('s\u00e4ilyt\u00e4'); 
var _UDS_MSG_SEARCHCONTROL_INCLUDE = ('sis\u00e4llyt\u00e4'); 
var _UDS_MSG_SEARCHCONTROL_COPY = ('kopioi'); 
var _UDS_MSG_SEARCHCONTROL_CLOSE = ('sulje'); 
var _UDS_MSG_SEARCHCONTROL_SPONSORED_LINKS = ('Sponsoroidut linkit'); 
var _UDS_MSG_SEARCHCONTROL_SEE_MORE = ('katso lis\u00e4\u00e4...'); 
var _UDS_MSG_SEARCHCONTROL_WATERMARK = ('valinta Googlesta'); 
var _UDS_MSG_SEARCHER_CONFIG_SET_LOCATION = ('Hakusijainti'); 
var _UDS_MSG_SEARCHER_CONFIG_DISABLE_ADDRESS_LOOKUP = ('Poista osoitetarkistus k\u00e4yt\u00f6st\u00e4'); 
var _UDS_MSG_SEARCHER_NEWS = ('Uutiset'); 
function _UDS_MSG_MINUTES_AGO(AGE_MINUTES_AGO) {return ('' + AGE_MINUTES_AGO + ' minuuttia sitten');} 
var _UDS_MSG_ONE_HOUR_AGO = ('1 tunti sitten'); 
function _UDS_MSG_HOURS_AGO(AGE_HOURS_AGO) {return ('' + AGE_HOURS_AGO + ' tuntia sitten');} 
function _UDS_MSG_NEWS_ALL_N_RELATED(NUMBER) {return ('kaikki ' + NUMBER + ' aiheeseen liittyv\u00e4\u00e4');} 
var _UDS_MSG_NEWS_RELATED = ('Aiheeseen liittyvi\u00e4 artikkeleita'); 
var _UDS_MSG_BRANDING_STRING = ('hakukoneena Google'); 
var _UDS_MSG_SORT_BY_DATE = ('Lajittele p\u00e4iv\u00e4yksen mukaan'); 
var _UDS_MSG_MONTH_ABBR_JAN = ('tam'); 
var _UDS_MSG_MONTH_ABBR_FEB = ('hel'); 
var _UDS_MSG_MONTH_ABBR_MAR = ('maa'); 
var _UDS_MSG_MONTH_ABBR_APR = ('huh'); 
var _UDS_MSG_MONTH_ABBR_MAY = ('tou'); 
var _UDS_MSG_MONTH_ABBR_JUN = ('kes'); 
var _UDS_MSG_MONTH_ABBR_JUL = ('hei'); 
var _UDS_MSG_MONTH_ABBR_AUG = ('elo'); 
var _UDS_MSG_MONTH_ABBR_SEP = ('syy'); 
var _UDS_MSG_MONTH_ABBR_OCT = ('lok'); 
var _UDS_MSG_MONTH_ABBR_NOV = ('mar'); 
var _UDS_MSG_MONTH_ABBR_DEC = ('jou'); 
var _UDS_MSG_DIRECTIONS = ('ohjeet perille'); 
var _UDS_MSG_CLEAR_RESULTS = ('poista tulokset'); 
var _UDS_MSG_SHOW_ONE_RESULT = ('n\u00e4yt\u00e4 yksi tulos'); 
var _UDS_MSG_SHOW_MORE_RESULTS = ('n\u00e4yt\u00e4 lis\u00e4\u00e4 tuloksia'); 
var _UDS_MSG_SHOW_ALL_RESULTS = ('n\u00e4yt\u00e4 kaikki tulokset'); 
var _UDS_MSG_SETTINGS = ('asetukset'); 
var _UDS_MSG_SEARCH = ('haku'); 
var _UDS_MSG_SEARCH_UC = ('Haku'); 
var _UDS_MSG_POWERED_BY = ('tarjoaa'); 
function _UDS_MSG_LOCAL_ATTRIBUTION(LOCAL_RESULTS_PROVIDER) {return ('Yritystiedot tarjosi ' + LOCAL_RESULTS_PROVIDER);} 
var _UDS_MSG_SEARCHER_BOOK = ('Kirja'); 
function _UDS_MSG_FOUND_ON_PAGE(FOUND_ON_PAGE) {return ('Sivu ' + FOUND_ON_PAGE);} 
function _UDS_MSG_TOTAL_PAGE_COUNT(PAGE_COUNT) {return ('' + PAGE_COUNT + ' sivua');} 
var _UDS_MSG_SEARCHER_BY = ('kirjoittanut'); 
var _UDS_MSG_SEARCHER_CODE = ('Koodi'); 
var _UDS_MSG_UNKNOWN_LICENSE = ('Tuntematon k\u00e4ytt\u00f6lupa'); 
var _UDS_MSG_SEARCHER_GSA = ('Search Appliance'); 
var _UDS_MSG_SEARCHCONTROL_MORERESULTS = ('Lis\u00e4\u00e4 tuloksia'); 
var _UDS_MSG_SEARCHCONTROL_PREVIOUS = ('Edellinen'); 
var _UDS_MSG_SEARCHCONTROL_NEXT = ('Seuraava'); 
var _UDS_MSG_GET_DIRECTIONS = ('Hanki ajo-ohjeet'); 
var _UDS_MSG_GET_DIRECTIONS_TO_HERE = ('paikkaan Y'); 
var _UDS_MSG_GET_DIRECTIONS_FROM_HERE = ('Paikasta X'); 
var _UDS_MSG_CLEAR_RESULTS_UC = ('Poista tulokset'); 
var _UDS_MSG_SEARCH_THE_MAP = ('etsi kartalta'); 
var _UDS_MSG_SCROLL_THROUGH_RESULTS = ('selaa tuloksia'); 
var _UDS_MSG_EDIT_TAGS = ('muokkaa koodia'); 
var _UDS_MSG_TAG_THIS_SEARCH = ('muista t\u00e4m\u00e4 haku'); 
var _UDS_MSG_SEARCH_STRING = ('haun merkkijono'); 
var _UDS_MSG_OPTIONAL_LABEL = ('valinnainen otsikko'); 
var _UDS_MSG_DELETE = ('poista'); 
var _UDS_MSG_DELETED = ('poistettu'); 
var _UDS_MSG_CANCEL = ('peruuta'); 
var _UDS_MSG_UPLOAD_YOUR_VIDEOS = ('lataa oma videosi sivustoon'); 
var _UDS_MSG_IM_DONE_WATCHING = ('sulje videonkatseluohjelma'); 
var _UDS_MSG_CLOSE_VIDEO_PLAYER = ('sulje videonkatseluohjelma'); 
var _UDS_MSG_NO_RESULTS = ('Ei tuloksia'); 
var _UDS_MSG_LINKEDCSE_ERROR_RESULTS = ('T\u00e4sm\u00e4hakukone lataa parhaillaan. Yrit\u00e4 uudelleen muutaman sekunnin kuluttua.'); 
var _UDS_MSG_COUPONS = ('Kupongit'); 
var _UDS_MSG_BACK = ('takaisin'); 
var _UDS_MSG_SUBSCRIBE = ('Tilaa'); 
var _UDS_MSG_SEARCHER_PATENT = ('Patentti'); 
var _UDS_MSG_USPAT = ('US Pat.'); 
var _UDS_MSG_USPAT_APP = ('US Pat. App'); 
var _UDS_MSG_PATENT_FILED = ('Hakemus j\u00e4tetty'); 
var _UDS_MSG_ADS_BY_GOOGLE = ('Google-mainokset');
var a=false,b=null,g=true,h=encodeURIComponent,k=google_exportSymbol,aa=_UDS_CONST_SHORT_DATE_PATTERN,m=window,o=google,ba=navigator,ca=parseInt,da=parseFloat,ea=_UDS_CONST_LOCALE,q=document,r=Math;function s(c,d){return c.title=d}function t(c,d){return c.className=d}function fa(c,d){return c.input=d}function ga(c,d){return c.width=d}function ha(c,d){return c.checked=d}function v(c,d){return c.innerHTML=d}function ia(c,d){return c.value=d}function ja(c,d){return c.type=d}
function ka(c,d){return c.onclick=d}function ma(c,d){return c.display=d}function na(c,d){return c.height=d}
var w="appendChild",oa="push",y="length",pa="title",A="prototype",B="cursor",qa="className",ra="clearTimeout",D="input",E="width",sa="Version",ta="round",ua="checked",va="setTimeout",F="replace",wa="split",xa="floor",ya="content",za="value",Aa="location",Ba="indexOf",Ca="getComputedStyle",H="style",Ea="close",I="search",Fa="call",Ga="match",Ha="focus",J="createElement",Ia="setAttribute",K="loader",Ja="currentStyle",Ka="cloneNode",La="type",Ma="apply",Na="ServiceBase",Oa="CurrentLocale",L="execute",
Pa="height",Qa="toLowerCase";if(!o[I].NoOldNames){k("UDS_ServiceBase",o[K][Na]);k("UDS_OriginalAppPath",o[K].OriginalAppPath);k("UDS_ApiKey",o[K].ApiKey);k("UDS_KeyVerified",o[K].KeyVerified);k("UDS_LoadFailure",o[K].LoadFailure);k("UDS_CurrentLocale",ea);k("UDS_ShortDatePattern",aa);k("UDS_Version",o[I][sa]);k("UDS_JSHash",o[I].JSHash)}var Ra=Ra||{};if(!M)var M=k;if(!N)var N=google_exportProperty;var O={};O.blank="&nbsp;";O.image=_UDS_MSG_SEARCHER_IMAGE;O.web=_UDS_MSG_SEARCHER_WEB;O.blog=_UDS_MSG_SEARCHER_BLOG;O.video=_UDS_MSG_SEARCHER_VIDEO;O.local=_UDS_MSG_SEARCHER_LOCAL;O.news=_UDS_MSG_SEARCHER_NEWS;O.book=_UDS_MSG_SEARCHER_BOOK;O.patent="Patent";O["ads-by-google"]=_UDS_MSG_ADS_BY_GOOGLE;O.save=_UDS_MSG_SEARCHCONTROL_SAVE;O.keep=_UDS_MSG_SEARCHCONTROL_KEEP;O.include=_UDS_MSG_SEARCHCONTROL_INCLUDE;O.copy=_UDS_MSG_SEARCHCONTROL_COPY;O.close=_UDS_MSG_SEARCHCONTROL_CLOSE;
O["sponsored-links"]=_UDS_MSG_SEARCHCONTROL_SPONSORED_LINKS;O["see-more"]=_UDS_MSG_SEARCHCONTROL_SEE_MORE;O.watermark=_UDS_MSG_SEARCHCONTROL_WATERMARK;O["search-location"]=_UDS_MSG_SEARCHER_CONFIG_SET_LOCATION;O["disable-address-lookup"]=_UDS_MSG_SEARCHER_CONFIG_DISABLE_ADDRESS_LOOKUP;O["sort-by-date"]=_UDS_MSG_SORT_BY_DATE;O.pbg=_UDS_MSG_BRANDING_STRING;O["n-minutes-ago"]=_UDS_MSG_MINUTES_AGO;O["n-hours-ago"]=_UDS_MSG_HOURS_AGO;O["one-hour-ago"]=_UDS_MSG_ONE_HOUR_AGO;O["all-n-related"]=_UDS_MSG_NEWS_ALL_N_RELATED;
O["related-articles"]=_UDS_MSG_NEWS_RELATED;O["page-count"]=_UDS_MSG_TOTAL_PAGE_COUNT;var P=[];P[0]=_UDS_MSG_MONTH_ABBR_JAN;P[1]=_UDS_MSG_MONTH_ABBR_FEB;P[2]=_UDS_MSG_MONTH_ABBR_MAR;P[3]=_UDS_MSG_MONTH_ABBR_APR;P[4]=_UDS_MSG_MONTH_ABBR_MAY;P[5]=_UDS_MSG_MONTH_ABBR_JUN;P[6]=_UDS_MSG_MONTH_ABBR_JUL;P[7]=_UDS_MSG_MONTH_ABBR_AUG;P[8]=_UDS_MSG_MONTH_ABBR_SEP;P[9]=_UDS_MSG_MONTH_ABBR_OCT;P[10]=_UDS_MSG_MONTH_ABBR_NOV;P[11]=_UDS_MSG_MONTH_ABBR_DEC;O["month-abbr"]=P;O.directions=_UDS_MSG_DIRECTIONS;
O["clear-results"]=_UDS_MSG_CLEAR_RESULTS;O["show-one-result"]=_UDS_MSG_SHOW_ONE_RESULT;O["show-more-results"]=_UDS_MSG_SHOW_MORE_RESULTS;O["show-all-results"]=_UDS_MSG_SHOW_ALL_RESULTS;O.settings=_UDS_MSG_SETTINGS;O.search=_UDS_MSG_SEARCH;O["search-uc"]=_UDS_MSG_SEARCH_UC;O["powered-by"]=_UDS_MSG_POWERED_BY;O.sa=_UDS_MSG_SEARCHER_GSA;O.by=_UDS_MSG_SEARCHER_BY;O.code=_UDS_MSG_SEARCHER_CODE;O["unknown-license"]=_UDS_MSG_UNKNOWN_LICENSE;O["more-results"]=_UDS_MSG_SEARCHCONTROL_MORERESULTS;
O.previous=_UDS_MSG_SEARCHCONTROL_PREVIOUS;O.next=_UDS_MSG_SEARCHCONTROL_NEXT;O["get-directions"]=_UDS_MSG_GET_DIRECTIONS;O["to-here"]=_UDS_MSG_GET_DIRECTIONS_TO_HERE;O["from-here"]=_UDS_MSG_GET_DIRECTIONS_FROM_HERE;O["clear-results-uc"]=_UDS_MSG_CLEAR_RESULTS_UC;O["search-the-map"]=_UDS_MSG_SEARCH_THE_MAP;O["scroll-results"]=_UDS_MSG_SCROLL_THROUGH_RESULTS;O["edit-tags"]=_UDS_MSG_EDIT_TAGS;O["tag-search"]=_UDS_MSG_TAG_THIS_SEARCH;O["search-string"]=_UDS_MSG_SEARCH_STRING;O["optional-label"]=_UDS_MSG_OPTIONAL_LABEL;
O["delete"]=_UDS_MSG_DELETE;O.deleted=_UDS_MSG_DELETED;O.cancel=_UDS_MSG_CANCEL;O["upload-video"]=_UDS_MSG_UPLOAD_YOUR_VIDEOS;O["im-done"]=_UDS_MSG_IM_DONE_WATCHING;O["close-player"]=_UDS_MSG_CLOSE_VIDEO_PLAYER;O["no-results"]=_UDS_MSG_NO_RESULTS;O["linked-cse-error-results"]=_UDS_MSG_LINKEDCSE_ERROR_RESULTS;O.back=_UDS_MSG_BACK;O.subscribe=_UDS_MSG_SUBSCRIBE;O["us-pat"]="US Pat.";O["us-pat-app"]="US Pat. App";O["us-pat-filed"]="Filed";function Sa(c,d){var e=function(){};e.prototype=d[A];c.prototype=new e;c[A].Ze=function(f){var j=Array[A].splice[Ma](arguments,[1,arguments[y]]);return f[Ma](c,j)}}var _json_cache_defeater_=(new Date).getTime(),_json_request_require_prep=g;function Ta(c,d){if(Ua("msie")&&Va("msie 6.0")){var e=Q(this,Wa,[c,d]);m[va](e,0)}else Wa(c,d)}function Ya(c){_json_request_require_prep=a;Ta(c,b);_json_request_require_prep=g}
function Wa(c,d){var e=q.getElementsByTagName("head")[0],f=q[J]("script");ja(f,"text/javascript");f.charset="utf-8";var j=_json_request_require_prep?c+"&key="+o[K].ApiKey+"&v="+d:c;if(Ua("msie")||Za())j=j+"&nocache="+_json_cache_defeater_++;f.src=j;var i=function(){f.onload=b;f.parentNode.removeChild(f);delete f},n=function(l){var p=(l?l:m.event).target?(l?l:m.event).target:(l?l:m.event).srcElement;if(p.readyState=="loaded"||p.readyState=="complete"){p.onreadystatechange=b;i()}};if(ba.product=="Gecko")f.onload=
i;else f.onreadystatechange=n;e[w](f)}function $a(c,d){return function(){return d[Ma](c,arguments)}}function Q(c,d,e){return function(){return d[Ma](c,e)}}function ab(c){while(c.firstChild)c.removeChild(c.firstChild)}function bb(c,d){if(c)try{ab(c);c[w](d)}catch(e){}return d}function R(c,d){try{c[w](d)}catch(e){}return d}function cb(c,d){v(c,d)}function S(c,d){var e=q[J]("div");if(c)v(e,c);if(d)t(e,d);return e}function T(c){var d=q[J]("div");if(c)t(d,c);return d}
function db(c,d){var e=q[J]("span");c&&R(e,q.createTextNode(c?c:""));if(d)t(e,d);return e}function eb(c,d,e){var f=q[J]("table");f[Ia]("cellSpacing",c?c:0);f[Ia]("cellPadding",d?d:0);if(e)t(f,e);return f}function fb(c,d,e){var f=c.insertRow(-1);f||alert(f);for(var j=0;j<d;j++)V(f,e);return f}function V(c,d){var e=c.insertCell(-1);if(d)t(e,d);return e}function gb(c,d,e,f){var j=q[J]("img");j.src=c;if(d)ga(j,d);if(e)na(j,e);if(f)t(j,f);return j}
function hb(c,d,e,f){var j;if(ib&&!jb){j=T(f);j[H].filter='progid:DXImageTransform.Microsoft.AlphaImageLoader(src="'+c+'")';ga(j[H],d+"px");na(j[H],e+"px")}else j=gb(c,b,b,f);return j}function kb(c,d,e,f){var j;if(Ua("msie")){j=T(f);j[H].filter='progid:DXImageTransform.Microsoft.AlphaImageLoader(src="'+c+'")';ga(j[H],d+"px");na(j[H],e+"px")}else j=gb(c,b,b,f);return j}
function lb(c,d,e,f,j){var i=q[J]("a");i.href=c;if(d)f?R(i,db(d,f)):R(i,q.createTextNode(d?d:""));if(e)i.target=e;if(j)s(i,j);return i}function W(c,d,e,f,j){var i=S(b,f),n=q[J]("a");n.href=c;v(n,d);if(f)t(n,f);if(e)n.target=e;if(j)s(n,j);i[w](n);return i}function mb(c){var d=q[J]("form");if(c)t(d,c);return d}function nb(c,d){var e=q[J]("input");ja(e,"submit");ia(e,c);if(d)t(e,d);return e}
function ob(c,d,e){var f=q[J]("input");f[Ia]("autoComplete","off");ja(f,"text");if(c==-1)X(f,"util-css-expand");else f.size=c>0?c:10;d&&X(f,d);if(e)ia(f,e);return f}function pb(c,d,e,f){var j=q[J]("input");ja(j,"checkbox");j.name=c;ia(j,d);if(f)t(j,f);if(e)ha(j,e);return j}function Y(c,d){t(c,d)}function X(c,d){qb(c,d)}function Z(c,d){rb(c,d)}function sb(c,d){if(c==b||c[qa]==b)return a;var e=c[qa][wa](" ");for(var f=0;f<e[y];f++)if(e[f]==d)return g;return a}
function qb(c,d){if(sb(c,d))return;c.className+=" "+d}function rb(c,d){if(c[qa]==b)return;var e=c[qa][wa](" "),f=[],j=a;for(var i=0;i<e[y];i++)if(e[i]!=d)e[i]&&f[oa](e[i]);else j=g;if(j)t(c,f.join(" "))}function tb(c){if(ub!="")return ub;var d=c[Qa]()[wa](".");if(d[y]<2)ub=".com";var e=d.pop(),f=d.pop();ub=e[y]==2?vb[f]&&vb[f][e]==1?"."+f+"."+e:"."+e:".com";return ub}
var ub="",vb={Sd:{hf:1,mf:1,uf:1,id:1,vf:1,"in":1,xf:1,zf:1,Af:1,Bf:1,Ef:1,Nf:1,bg:1,fg:1,gg:1,kg:1,lg:1,og:1},jf:{$e:1,bf:1,df:1,ef:1,ff:1,gf:1,Sd:1,nf:1,"do":1,of:1,pf:1,qf:1,rf:1,sf:1,tf:1,yf:1,Ff:1,Gf:1,Hf:1,If:1,Jf:1,Kf:1,Lf:1,Mf:1,Rf:1,Sf:1,Tf:1,Uf:1,Vf:1,Wf:1,Yf:1,Zf:1,ag:1,cg:1,dg:1,eg:1,ig:1,jg:1,ng:1},Of:{af:1}};
function wb(c){var d=c[Qa]()[wa](".");if(d[y]<2)return a;var e=d.pop(),f=d.pop();if((f=="igoogle"||f=="gmodules"||f=="googlesyndication")&&e=="com")return g;if(e[y]==2&&d[y]>0)if(vb[f]&&vb[f][e]==1)f=d.pop();return f=="google"}function Ua(c){if(c in xb)return xb[c];return xb[c]=ba.userAgent[Qa]()[Ba](c)!=-1}function Va(c){if(c in Ab)return Ab[c];return Ab[c]=ba.appVersion[Qa]()[Ba](c)!=-1}var xb={},Ab={};function Za(){return Ua("safari")||Ua("konqueror")}var ib,jb,Bb,Cb,Db,Eb,Fb;
function Gb(){if(m.Ye){ib=g;if(m.XMLHttpRequest)jb=g;else Bb=g}else if(m.Qf)Cb=g;else if(q.childNodes&&!q.all&&!ba.taintEnabled){Db=g;if(ba.userAgent[Ba]("iPhone")>0)Eb=g}else if(q.getBoxObjectFor!=b)Fb=g}Gb();function Hb(c){this.Fb=c+"branding";this.ub=c+"branding-vertical";this.wf=c+"branding-img";this.hg=c+"branding-user-defined";this.gd=c+"branding-img-noclear";this.Rd=c+"branding-clickable";this.text=c+"branding-text"}
function Ib(c,d,e,f){var j=new Hb(c),i=T(j.Fb),n=eb(b,b,j.Fb);R(i,n);var l=!e;if(!l){X(i,j.ub);X(n,j.ub)}var p=fb(n,0),u,x;if(l){u=p;x=p}else{u=p;x=fb(n,0)}var z="/css/small-logo.png",C=51,G=15;if(f)if(typeof f=="string")if(f[Ga](/^http:\/\/www\.youtube\.com/)){z="/css/youtube-logo-55x24.png";C=55;G=24;X(i,j.Fb+"-youtube");if(!l){X(i,j.ub+"-youtube");X(n,j.ub+"-youtube")}}var U=V(u,j.text),$=V(x,j.gd),Da=S(O["powered-by"],j.text),la=hb(o[K][Na]+z,C,G,j.gd);R(U,Da);if(f){var Xa="http://www.google.com";
if(typeof f=="string"&&(f[Ga](/^http:\/\/[a-z]*\.google\.com/)||f[Ga](/^http:\/\/www\.youtube\.com/)))Xa=f;var yb=lb(Xa,b,"_BLANK");t(yb,j.Rd);R(yb,la);R($,yb)}else R($,la);if(d){var zb;zb=typeof d=="string"?q.getElementById(d):d;ab(zb);R(zb,i)}return i};var Jb="gs-result",Kb="gs-error-result",Lb="gs-no-results-result",Mb="gs-spacer",Nb="gs-title",Ob="gs-snippet",Pb="gs-visibleUrl",Qb="gs-visibleUrl-long",Rb="gs-visibleUrl-short",Sb="gs-watermark",Tb="gs-results-attribution",Ub="gs-address",Vb="gs-street",Wb="gs-city",Xb="gs-region",Yb="gs-country",Zb="gs-phone",$b="gs-street gs-addressLine",ac="gs-city gs-addressLine",bc="gs-addressLine",cc="gs-directions",dc="gs-directions-to-from",ec="gs-label",fc="gs-secondary-link",gc="gs-author",hc="gs-publisher",
ic="gs-location",jc="gs-clusterUrl",kc="gs-image-box",lc="gs-image-box gs-book-image-box",mc="gs-text-box",nc="gs-metadata",oc="gs-row-1",pc="gs-row-2",qc="gs-pages",rc="gs-page-edge",sc="gs-image",tc="gs-size",uc="gs-pageCount",vc="gs-publishedDate",wc="gs-relativePublishedDate",xc="gs-patent-info",yc="gs-patent-number",zc="gs-patent-image",Ac="gsc-control",Bc="gsc-narrow",Cc="gsc-search-box",Dc="gsc-search-button",Ec="gsc-clear-button",Fc="gsc-input",Gc="gsc-branding",Hc="gsc-branding-img",Ic="gsc-branding-user-defined",
Jc="gsc-branding-img-noclear",Kc="gsc-branding-clickable",Lc="gsc-branding-text",Mc="gsc-resultsRoot",Nc="gsc-results",Oc="gsc-result",Pc="gsc-resultsHeader",Qc="gsc-resultsbox-invisible",Rc="gsc-resultsbox-visible",Sc="gsc-expansionArea",Tc="gsc-trailing-more-results",Uc="gsc-cursor-box",Vc="gsc-cursor",Wc="gsc-cursor-page",Xc="gsc-cursor-current-page",Yc="gsc-adBlock",Zc="gsc-adBlockInvisible",$c="gsc-adBlockVertical",ad="gsc-adBlockVerticalInvisible",bd="gsc-ad",cd="gsc-thinWrapper",dd="gsc-twiddleRegionCell",
ed="gsc-configLabelCell",fd="gsc-configLabel",gd="gsc-twiddle",hd="gsc-twiddle-closed",id="gsc-twiddle-opened",jd="gsc-title",kd="gsc-stats",ld="gsc-keeper",md="gsc-result-selector gsc-one-result",nd="gsc-result-selector gsc-more-results",od="gsc-result-selector gsc-all-results",pd="gsc-results-selector",qd="gsc-one-result-active",rd="gsc-more-results-active",sd="gsc-all-results-active",td="gsc-tabsArea",ud="gsc-tabsAreaInvisible",vd="gsc-tabHeader",wd="gsc-tabhActive",xd="gsc-tabhInactive",yd="gsc-tabdActive",
zd="gsc-tabdInactive",Ad="gsc-tabData",Bd="gsc-config",Cd="gsc-configSetting",Dd="gsc-configSettingSubmit",Ed="gsc-configSettingCheckbox",Fd="gsc-configSettingCheckboxLabel",Gd="gsc-configSettingInput",Hd="gsc-configSettingInputLabel",Id="gsc-locationConfig",Jd="gsc-video-player";o[I].a=function(){this.kf=b;this.$=b;this.Xe=0;this.cc=0;this.bd=g;this.I={width:100,height:75};this.ya=o[I].a.Ra;this.ld=1;this.ta(o[I].a.X);this.$c();this.Jb=b;this.Lb=b;this.bc=b;this.Vb=b;this.eb=b;this.db=b;this.mb=b;this.B="null";this.F=b;this.t=b;this.gwsUrl=b;this.ja=[];this.ed=typeof m==="object"&&m[Aa]&&m[Aa].hostname&&m[Aa].hostname!=""?tb(m[Aa].hostname):".com";this.Va=b;this.Za=b};M("google.search.Search",o[I].a);o[I].a.gc=o[K][Na];N(o[I].a,"BASE",o[I].a.gc);o[I].a.wa="large";
N(o[I].a,"LARGE_RESULTSET",o[I].a.wa);o[I].a.X="small";N(o[I].a,"SMALL_RESULTSET",o[I].a.X);o[I].a.Cd=8;N(o[I].a,"LARGE_RESULTS",o[I].a.Cd);o[I].a.Jd=4;N(o[I].a,"SMALL_RESULTS",o[I].a.Jd);o[I].a.yc=5000;N(o[I].a,"KEEP_SWEEPER_DELAY",o[I].a.yc);o[I].a.Fd="_top";N(o[I].a,"LINK_TARGET_TOP",o[I].a.Fd);o[I].a.Ed="_self";N(o[I].a,"LINK_TARGET_SELF",o[I].a.Ed);o[I].a.Dd="_parent";N(o[I].a,"LINK_TARGET_PARENT",o[I].a.Dd);o[I].a.Ra="_blank";N(o[I].a,"LINK_TARGET_BLANK",o[I].a.Ra);o[I].a.ea="order-by-relevance";
N(o[I].a,"ORDER_BY_RELEVANCE",o[I].a.ea);o[I].a.da="order-by-date";N(o[I].a,"ORDER_BY_DATE",o[I].a.da);o[I].a.Ac="order-by-ascending-date";N(o[I].a,"ORDER_BY_ASCENDING_DATE",o[I].a.Ac);o[I].a.gb="restrict-type";N(o[I].a,"RESTRICT_TYPE",o[I].a.gb);o[I].a.xb="restrict-safesearch";N(o[I].a,"RESTRICT_SAFESEARCH",o[I].a.xb);o[I].a.Ab="active";N(o[I].a,"SAFESEARCH_STRICT",o[I].a.Ab);o[I].a.zb="off";N(o[I].a,"SAFESEARCH_OFF",o[I].a.zb);o[I].a.yb="moderate";N(o[I].a,"SAFESEARCH_MODERATE",o[I].a.yb);
o[I].a.wb="restrict-extended";N(o[I].a,"RESTRICT_EXTENDED_ARGS",o[I].a.wb);o[I].a.Te=O;N(o[I].a,"strings",o[I].a.Te);o[I].a[A].xe=function(){var c=this.ga+"?hl="+o[I][Oa]+"&source=uds";c=this.t?c+this.t:c+"&q=";return this.oa&&this.oa!=""?this.oa:c};o[I].a[A].Le=function(c){this.F=c==b||c==""?b:c};N(o[I].a[A],"setQueryAddition",o[I].a[A].Le);
o[I].a[A].ra=function(c,d,e){var f=o[I].a.gc+this.ua+"?callback="+c+"&context="+d+"&lstkp="+this.Qd()+"&rsz="+this.Ma+"&hl="+o[I][Oa];if(this.ed)f+="&gss="+this.ed;if(o[I].JSHash)f+="&sig="+o[I].JSHash;if(e)f+="&start="+e;return f};o[I].a[A].ab=function(c){this.ya=c};N(o[I].a[A],"setLinkTarget",o[I].a[A].ab);o[I].a[A].s=function(){return this.ya&&this.ya!=""?this.ya:b};o[I].a[A].ke=function(){this.Xe++;this.cc++;this.mb&&m[ra](this.mb);this.mb=m[va](Q(this,this[L],[b]),o[I].a.yc)};
o[I].a[A].Qd=function(){m[ra](this.mb);var c=this.cc;this.cc=0;return c};o[I].a[A].dd=function(){if(this.Jb==b)this.Jb="gsc-"+this.B+"Result";return this.Jb};o[I].a[A].ba=function(){if(this.Lb==b)this.Lb="gs-"+this.B+"Result";return this.Lb};o[I].a[A].ie=function(){if(this.bc==b)this.bc=O[this.B];return this.eb?this.eb:this.bc};o[I].a[A].ge=function(){if(this.Vb==b)this.Vb=O[this.B];return this.eb?this.eb:this.Vb};o[I].a[A].he=function(){return this.Ma};N(o[I].a[A],"getResultSetSize",o[I].a[A].he);
o[I].a[A].ta=function(c){switch(c){case o[I].a.wa:this.Ma=o[I].a.wa;break;default:case o[I].a.X:this.Ma=o[I].a.X;break}};N(o[I].a[A],"setResultSetSize",o[I].a[A].ta);o[I].a[A].execute=function(c){var d=this.aa(c,b,b);if(m._googleudsextrastuff)d=d+m._googleudsextrastuff;this.cursor=b;this.ne=c;Ta(d,o[I][sa]);if(this.ja&&this.ja[y]>0)for(var e=0;e<this.ja[y];e++)this.ja[e][L](c)};N(o[I].a[A],"execute",o[I].a[A][L]);
o[I].a[A].fd=function(c){if(this[B]&&c<this[B].pages[y]){var d=this.aa(this.ne,b,b,this[B].pages[c].start);this.cursor=b;Ta(d,o[I][sa])}};N(o[I].a[A],"gotoPage",o[I].a[A].fd);o[I].a[A].Ld=function(c){this.ja&&this.ja[oa](c)};N(o[I].a[A],"addRelatedSearcher",o[I].a[A].Ld);o[I].a[A].fe=function(c,d,e){return this.aa(c,d,e)+"&key="+o[K].ApiKey+"&v="+o[I][sa]};N(o[I].a[A],"getExecuteUrl",o[I].a[A].fe);
o[I].a[A].ma=function(c){var d=O.watermark+" - "+this.Td(),e=W("http://code.google.com/apis/ajaxsearch/faq.html",d,"_blank",Sb);R(c,e)};o[I].a[A].Td=function(){var c=new Date;return c.getMonth()+1+"/"+c.getFullYear()};
o[I].a[A].Ja=function(c){var d,e=c.getFullYear(),f=c.getMonth(),j=O["month-abbr"][f],i=c.getDate();if(i<10)i="0"+i;switch(o[I].ShortDatePattern){case "MDY":d=j+" "+i+", "+e;break;case "YMD":d=o[I][Oa]=="zh-CN"||o[I][Oa]=="zh-TW"?e+"\u5e74"+f+"\u6708"+i+"\u65e5":e+" "+j+" "+i;break;default:case "DMY":d=i+" "+j+" "+e;break}return d};N(o[I].a[A],"formatToShortDate",o[I].a[A].Ja);o[I].a.zc=3600000;o[I].a.Hd=60000;o[I].a.Gd=86400000;
o[I].a[A].Pb=function(c){var d=(new Date).getTime(),e=c.getTime(),f;if(d<e)return O["n-minutes-ago"](2);var j=d-e;if(j<o[I].a.zc){var i=r[xa](j/o[I].a.Hd);f=i<=1?2:i;return O["n-minutes-ago"](f)}if(j<o[I].a.Gd){var n=r[xa](j/o[I].a.zc);if(n<=1)return O["one-hour-ago"];else{f=n;return O["n-hours-ago"](f)}}return this.Ja(c)};N(o[I].a[A],"formatToRelativeDate",o[I].a[A].Pb);o[I].a[A].$c=function(){this.gwsUrl=b;this.Xf=b;this.results=[]};N(o[I].a[A],"clearResults",o[I].a[A].$c);
o[I].a[A].ae=function(){this.ad&&this.ad()};
o[I].a[A].O=function(c,d,e,f){if(c==b&&d==204)return;this.gwsUrl=b;if(this.results&&this.results[y]>0)for(var j=0;j<this.results[y];j++)this.results[j].html&&Kd(this.results[j].html);if(c&&c.results&&c.results[y]>0){this.results=c.results;if(c[B]&&c[B].moreResultsUrl)this.gwsUrl=this.oa&&this.oa!=""?this.oa:c[B].moreResultsUrl;else if(this.t&&this.ga)this.gwsUrl=this.xe()}else this.results=[];this.completionStatus=d;this.hashStatus=f;this.lf=e;this.od=c&&c.resultAttribution&&c.resultAttribution!=
b&&c.resultAttribution!=""?c.resultAttribution:b;if(c&&c[B]&&c[B].pages&&c[B].pages[y]>0)this.cursor=c[B];this.bd&&this.Od();this.ae()};N(o[I].a[A],"onSearchComplete",o[I].a[A].O);o[I].a[A].cd=function(){var c=b;if(this.od)c=S(this.od,Tb);return c};N(o[I].a[A],"getAttribution",o[I].a[A].cd);o[I].a[A].Od=function(){var c,d;for(c=0;c<this.results[y];c++){d=this.results[c];this.A(d)}};o[I].a[A].bb=function(c,d,e){e||(e=[b]);this.ad=Q(c,d,e)};N(o[I].a[A],"setSearchCompleteCallback",o[I].a[A].bb);
o[I].a.ca=function(c,d){var e=a,f;if(c[y])for(var j=0;j<c[y];j++)if(c[j]==b){c[j]=d;f=j;e=g;break}if(!e){f=c[y];c[oa](d)}return f};N(o[I].a,"AllocateCompletionMapContext",o[I].a.ca);o[I].a[A].Re=function(c){this.eb=c};N(o[I].a[A],"setUserDefinedLabel",o[I].a[A].Re);o[I].a[A].Qe=function(c){this.db=c};N(o[I].a[A],"setUserDefinedClassSuffix",o[I].a[A].Qe);o[I].a[A].Je=function(){this.bd=a};N(o[I].a[A],"setNoHtmlGeneration",o[I].a[A].Je);
o[I].a.Oa=function(c,d,e,f,j){var i=r.min(e[E]/c,e[Pa]/d),n=r.min(i,1),l={};ga(l,r[ta](c*n));na(l,r[ta](d*n));if(f){ga(f,l[E]);na(f,l[Pa]);if(j)f[H].left=(e[E]-l[E])/2+"px"}return l};N(o[I].a,"scaleImage",o[I].a.Oa);o[I].a.Xc=1;N(o[I].a,"VERTICAL_BRANDING",o[I].a.Xc);o[I].a.xd=2;N(o[I].a,"HORIZONTAL_BRANDING",o[I].a.xd);o[I].a.de=function(c,d,e){return Ib("gsc-",c,d&&d==o[I].a.Xc,e)};N(o[I].a,"getBranding",o[I].a.de);o[I].a.setOnLoadCallback=function(c,d){o.setOnLoadCallback(c,d)};
N(o[I].a,"setOnLoadCallback",o[I].a.setOnLoadCallback);var Ld;function Kd(c){Ld||(Ld=q[J]("DIV"));Ld[w](c);v(Ld,"")}o[I].a[A].be=function(c){var d=this.Va;if(c)d=c;var e={},f=T(this.ba());X(f,Jb);X(f,Kb);var j;j=S(d,Ob);R(f,j);e.html=f;return e};o[I].a[A].ce=function(c){var d=this.Za;if(c)d=c;var e={},f=T(this.ba());X(f,Jb);X(f,Lb);var j;j=S(d,Ob);R(f,j);e.html=f;return e};k("google.search.CurrentLocale",ea);k("google.search.ShortDatePattern",aa);o[I].p=function(){o[I].a[Fa](this);this.B="blog";this.ua="/GblogSearch";this.ga="http://blogsearch.google.com/blogsearch";this.o=b;this.J=a;this.Ha=g;this.$=$a(this,o[I].p[A].ia);this.Ga="gsc-blogConfig";this.j=b};M("google.search.BlogSearch",o[I].p);Sa(o[I].p,o[I].a);o[I].p.z="GblogSearch";N(o[I].p,"RESULT_CLASS",o[I].p.z);o[I].p.n=[];o[I].p.G=function(c,d,e,f,j){var i=0;if(c)i=ca(c,10);var n=o[I].p.n[i];o[I].p.n[i]=b;n.O(d,e,f,j)};N(o[I].p,"RawCompletion",o[I].p.G);
o[I].p[A].aa=function(c,d,e){var f;f=e==b?o[I].a.ca(o[I].p.n,this):e;var j;j=d==b?"google.search.BlogSearch.RawCompletion":d;var i=this.ra(j,f);if(c){var n,l=c;if(this.F)l=l+" "+this.F;if(this.o)l=l+" blogurl:"+this.o;n="&q="+h(l);if(this.J)n=n+"&scoring=d";i=i+n;this.t=n}return i};
o[I].p[A].A=function(c){c.html&&delete c.html;var d=T(this.ba());X(d,Jb);var e;e=W(c.postUrl,c[pa],this.s(),Nb);R(d,e);var f=new Date(c.publishedDate);e=S(this.Ja(f),vc);R(d,e);f=new Date(c.publishedDate);e=S(this.Pb(f),wc);R(d,e);e=S(c[ya],Ob);R(d,e);e=W(c.blogUrl,c.blogUrl,this.s(),Pb);R(d,e);c.html=d;this.ma(c.html)};N(o[I].p[A],"createResultHtml",o[I].p[A].A);o[I].p[A].Aa=function(c){this.o=c==b||c==""?b:c};N(o[I].p[A],"setSiteRestriction",o[I].p[A].Aa);
o[I].p[A].H=function(c){this.J=c==o[I].a.da?g:c==o[I].a.ea?a:a};N(o[I].p[A],"setResultOrder",o[I].p[A].H);o[I].p[A].ia=function(c,d){if(d)if(this.j==b){var e=T(Cd);this.j=pb(b,"0",this.J,Ed);R(e,this.j);R(e,S(O["sort-by-date"],Fd));var f=T(Dd);R(f,nb(O[Ea],Dd));R(e,f);R(c,e);this.j[Ha]()}else{ha(this.j,this.J);this.j[Ha]()}else if(this.j)this.j[ua]?this.H(o[I].a.da):this.H(o[I].a.ea)};o[I].l=function(){o[I].a[Fa](this);this.B="book";this.ua="/GbookSearch";this.ga="http://books.google.com/books";this.lb=a;this.dc=b};M("google.search.BookSearch",o[I].l);Sa(o[I].l,o[I].a);o[I].l.z="GbookSearch";N(o[I].l,"RESULT_CLASS",o[I].l.z);o[I].l.Wc="user-list";N(o[I].l,"USER_LIST",o[I].l.Wc);o[I].l.Oc=1;N(o[I].l,"TYPE_ALL_BOOKS",o[I].l.Oc);o[I].l.Sc=2;N(o[I].l,"TYPE_FULL_VIEW_BOOKS",o[I].l.Sc);o[I].l.n=[];
o[I].l.G=function(c,d,e,f,j){var i=0;if(c)i=ca(c,10);var n=o[I].l.n[i];o[I].l.n[i]=b;n.O(d,e,f,j)};N(o[I].l,"RawCompletion",o[I].l.G);o[I].l[A].aa=function(c,d,e,f){var j;j=e==b?o[I].a.ca(o[I].l.n,this):e;var i;i=d==b?"google.search.BookSearch.RawCompletion":d;var n=this.ra(i,j,f);if(c){var l,p=c;if(this.F)p=p+" "+this.F;l="&q="+h(p);if(this.lb)l=l+"&as_brr=1";if(this.dc)l=l+"&as_list="+this.dc;n=n+l;this.t=l}return n};
o[I].l[A].A=function(c){c.html&&delete c.html;c.thumbnailHtml=this.Kb(c);var d=T(this.ba());X(d,Jb);var e=T(mc),f=eb(),j=fb(f,0),i=V(j,kc),n=V(j,mc);R(i,c.thumbnailHtml[Ka](g));R(n,e);R(d,f);var l;l=W(c.unescapedUrl,c[pa],this.s(),Nb);R(e,l);l=S(O.by+"&nbsp;"+c.authors,gc);R(e,l);l=T(Mb);R(e,l);if(c.publishedYear){l=S(c.publishedYear,vc);R(e,l)}if(ca(c.pageCount,10)>0){l=S("-&nbsp;"+O["page-count"](c.pageCount),uc);R(e,l)}l=W("http://books.google.com","books.google.com",this.s(),Pb);R(e,l);c.html=
d;this.ma(c.html)};N(o[I].l[A],"createResultHtml",o[I].l[A].A);o[I].l[A].Kb=function(c){var d="http://books.google.com/googlebooks/",e=T(lc),f=T(oc),j=gb(d+"pages-trans.gif",b,b,qc);R(f,j);j=gb(d+"p_edge-trans.gif",b,b,rc);R(f,j);R(e,f);f=T(pc);var i=o[I].a.Oa(c.tbWidth,c.tbHeight,this.I);j=gb(c.tbUrl,i[E],i[Pa],sc);var n=lb(c.unescapedUrl,b,this.s(),sc);Y(n,sc);R(n,j);R(f,n);R(e,f);return e};
o[I].l[A].Q=function(c,d){if(c==o[I].a.gb)if(d)if(d==o[I].l.Oc)this.lb=a;else if(d==o[I].l.Sc)this.lb=g;else this.Q(c,b);else this.lb=a;else if(c==o[I].l.Wc)this.dc=d&&d[Ga](/^[a-zA-Z0-9\-_]*$/)?d:b};N(o[I].l[A],"setRestriction",o[I].l[A].Q);o[I].c=function(){o[I].a[Fa](this);this.ld=2;this.B="image";this.ua="/GimageSearch";this.ga="http://images.google.com/images";this.za=b;this.Sb=b;this.Rb=b;this.Tb=b;this.Ob=b;this.Xb=b;this.o=b;this.I={width:112,height:84}};M("google.search.ImageSearch",o[I].c);Sa(o[I].c,o[I].a);o[I].c.z="GimageSearch";N(o[I].c,"RESULT_CLASS",o[I].c.z);o[I].c.Gc="restrict-imagesize";N(o[I].c,"RESTRICT_IMAGESIZE",o[I].c.Gc);o[I].c.Bd=["icon"];N(o[I].c,"IMAGESIZE_SMALL",o[I].c.Bd);
o[I].c.Ad=["small","medium","large","xlarge"];N(o[I].c,"IMAGESIZE_MEDIUM",o[I].c.Ad);o[I].c.zd=["xxlarge"];N(o[I].c,"IMAGESIZE_LARGE",o[I].c.zd);o[I].c.yd=["huge"];N(o[I].c,"IMAGESIZE_EXTRA_LARGE",o[I].c.yd);o[I].c.Dc="restrict-coloration";N(o[I].c,"RESTRICT_COLORIZATION",o[I].c.Dc);o[I].c.hc="mono";N(o[I].c,"COLORIZATION_BLACK_AND_WHITE",o[I].c.hc);o[I].c.jc="gray";N(o[I].c,"COLORIZATION_GRAYSCALE",o[I].c.jc);o[I].c.ic="color";N(o[I].c,"COLORIZATION_COLOR",o[I].c.ic);o[I].c.Fc="restrict-filetype";
N(o[I].c,"RESTRICT_FILETYPE",o[I].c.Fc);o[I].c.nc="jpg";N(o[I].c,"FILETYPE_JPG",o[I].c.nc);o[I].c.oc="png";N(o[I].c,"FILETYPE_PNG",o[I].c.oc);o[I].c.mc="gif";N(o[I].c,"FILETYPE_GIF",o[I].c.mc);o[I].c.lc="bmp";N(o[I].c,"FILETYPE_BMP",o[I].c.lc);o[I].c.Hc="restrict-imagetype";N(o[I].c,"RESTRICT_IMAGETYPE",o[I].c.Hc);o[I].c.qc="face";N(o[I].c,"IMAGETYPE_FACES",o[I].c.qc);o[I].c.pc="clipart";N(o[I].c,"IMAGETYPE_CLIPART",o[I].c.pc);o[I].c.rc="news";N(o[I].c,"IMAGETYPE_NEWS",o[I].c.rc);o[I].c.sc="photo";
N(o[I].c,"IMAGETYPE_PHOTO",o[I].c.sc);o[I].c.Cc="restrict";N(o[I].c,"RESTRICT",o[I].c.Cc);o[I].c.Ec="cc_attribute";N(o[I].c,"RESTRICT_CREATIVE_COMMONS",o[I].c.Ec);o[I].c.n=[];o[I].c.G=function(c,d,e,f,j){var i=0;if(c)i=ca(c,10);var n=o[I].c.n[i];o[I].c.n[i]=b;n.O(d,e,f,j)};N(o[I].c,"RawCompletion",o[I].c.G);
o[I].c[A].aa=function(c,d,e,f){var j;j=e==b?o[I].a.ca(o[I].c.n,this):e;var i;i=d==b?"google.search.ImageSearch.RawCompletion":d;var n=this.ra(i,j,f);if(c){var l,p=c;if(this.F)p=p+" "+this.F;l="&q="+h(p);if(this.za)l=l+"&safe="+this.za;if(this.Sb)l=l+"&imgsz="+h(this.Sb);if(this.Rb)l=l+"&imgc="+h(this.Rb);if(this.Tb)l=l+"&imgtype="+h(this.Tb);if(this.Ob)l=l+"&as_filetype="+h(this.Ob);if(this.Xb)l=l+"&restrict="+h(this.Xb);if(this.o)l=l+"&as_sitesearch="+h(this.o);n=n+l;this.t=l;if(f&&f!=0)this.t=this.t+
"&start="+f}return n};
o[I].c[A].A=function(c){c.html&&delete c.html;var d=T(this.ba());X(d,Jb);var e=T(kc),f=o[I].a.Oa(c.tbWidth,c.tbHeight,this.I),j=gb(c.tbUrl,f[E],f[Pa],sc);j[H].left=(this.I[E]-f[E])/2+"px";s(j,c.titleNoFormatting+" ("+c.visibleUrl+")");var i=lb(c.unescapedUrl,b,this.s(),sc);Y(i,sc);R(i,j);R(e,i);R(d,e);var n=T(mc),l;l=S(c[ya],Ob);s(l,c.contentNoFormatting);R(n,l);l=S(c[E]+" x "+c[Pa],tc);R(n,l);l=W(c.originalContextUrl,c.visibleUrl,this.s(),Pb);s(l,c.visibleUrl);R(n,l);R(d,n);c.html=d;this.ma(c.html)};
N(o[I].c[A],"createResultHtml",o[I].c[A].A);o[I].c[A].Aa=function(c){this.o=c};N(o[I].c[A],"setSiteRestriction",o[I].c[A].Aa);
o[I].c[A].Q=function(c,d){if(c==o[I].a.xb)this.za=d?d==o[I].a.Ab||d==o[I].a.zb?d:d==o[I].a.yb?b:b:b;else if(c==o[I].c.Gc)this.Sb=d?d.join("|"):b;else if(c==o[I].c.Dc)this.Rb=d?d==o[I].c.hc||d==o[I].c.jc||d==o[I].c.ic?d:b:b;else if(c==o[I].c.Fc)this.Ob=d?d==o[I].c.nc||d==o[I].c.oc||d==o[I].c.mc||d==o[I].c.lc?d:b:b;else if(c==o[I].c.Hc)this.Tb=d?d==o[I].c.qc||d==o[I].c.pc||d==o[I].c.rc||d==o[I].c.sc?d:b:b;else if(c==o[I].c.Cc)this.Xb=d?d==o[I].c.Ec?d:b:b};N(o[I].c[A],"setRestriction",o[I].c[A].Q);o[I].e=function(){o[I].a[Fa](this);this.W=b;this.V="San Francisco, CA";this.Z={y:37.77916,x:-122.42009};this.Fa=b;this.Ya=g;this.Sa=a;this.La=b;this.Ha=g;this.$=$a(this,this.ia);this.Ga=Id;this.B="local";this.ua="/GlocalSearch";this.ga="http://www.google.com/local";this.D=b;this.Ea=b};M("google.search.LocalSearch",o[I].e);Sa(o[I].e,o[I].a);o[I].e.z="GlocalSearch";N(o[I].e,"RESULT_CLASS",o[I].e.z);o[I].e.Rc="blended";N(o[I].e,"TYPE_BLENDED_RESULTS",o[I].e.Rc);o[I].e.Uc="kmlonly";
N(o[I].e,"TYPE_KMLONLY_RESULTS",o[I].e.Uc);o[I].e.Vc="localonly";N(o[I].e,"TYPE_LOCALONLY_RESULTS",o[I].e.Vc);o[I].e.ec="disabled";N(o[I].e,"ADDRESS_LOOKUP_DISABLED",o[I].e.ec);o[I].e.fc="enabled";N(o[I].e,"ADDRESS_LOOKUP_ENABLED",o[I].e.fc);o[I].e.Lc=17;N(o[I].e,"STATIC_MAP_ZOOM_FARTHEST",o[I].e.Lc);o[I].e.Kd=4;N(o[I].e,"STATIC_MAP_ZOOM_DEFAULT",o[I].e.Kd);o[I].e.Kc=0;N(o[I].e,"STATIC_MAP_ZOOM_CLOSEST",o[I].e.Kc);o[I].e.Eb=8;N(o[I].e,"STATIC_MAP_MAX_POINTS",o[I].e.Eb);o[I].e.we=3.141592653589;
o[I].e.Zd=6367000;o[I].e.We=16093;o[I].e.n=[];o[I].e.G=function(c,d,e,f,j){var i=0;if(c)i=ca(c,10);var n=o[I].e.n[i];o[I].e.n[i]=b;n.resultViewport=d&&d.viewport?d.viewport:b;n.O(d,e,f,j)};N(o[I].e,"RawCompletion",o[I].e.G);
o[I].e[A].aa=function(c,d,e,f){var j;j=e==b?o[I].a.ca(o[I].e.n,this):e;var i;i=d==b?"google.search.LocalSearch.RawCompletion":d;var n=this.ra(i,j,f),l="";if(c){l="&q="+h(c);n=n+l}this.mg=b;var p;if(this.W){var u,x;if(this.Ya){u=this.W.getCenterLatLng();x=this.W.getSpanLatLng();p="&sll="+u.y+","+u.x;p+="&sspn="+x[Pa]+","+x[E];p+=o[I].e.ib(u.y,u.x);n+=p;l+=p}else{u=this.W.getCenter();x=this.W.getBounds().toSpan().toUrlValue();p="&sll="+u.y+","+u.x;p+="&sspn="+x;p+=o[I].e.ib(u.y,u.x);n+=p;l+=p}}else if(this.Z){p=
"&sll="+this.Z.y+","+this.Z.x;if(this.Fa)p=p+"&sspn="+this.Fa.lat+","+this.Fa.lng;p+=o[I].e.ib(this.Z.y,this.Z.x);n+=p;l+=p}else if(this.V){p="&near="+h(this.V);n+=p;l+=p}if(this.Sa){n+="&nogeocode=t";l+="&nogeocode=t"}if(this.La){n+="&mrt="+h(this.La);l+="&mrt="+h(this.La)}if(l)this.t=l;return n};o[I].e.ib=function(c,d){var e=2*o[I].e.We/o[I].e.Zd*2*o[I].e.we,f=d-e,j=c+e,i=d+e;return"&gll="+r[xa]((c-e)*1000000)+","+r[xa](f*1000000)+","+r[xa](j*1000000)+","+r[xa](i*1000000)+"&llsep=500,500"};
N(o[I].e,"centerToGll",o[I].e.ib);
o[I].e[A].A=function(c){c.html&&delete c.html;var d=T(this.ba());X(d,Jb);var e;e=W(c.url,c[pa],this.s(),Nb);R(d,e);if(c.listingType=="kml"&&c[ya]&&c[ya]!=""){e=S(c[ya],Ob);R(d,e)}var f=T(Ub);if(c.addressLines&&c.addressLines[y]>0)for(var j=0;j<c.addressLines[y];j++){var i=c.addressLines[j],n=bc;if(j==0)n=$b;else if(j==1)n=ac;e=S(i,n);R(f,e)}else{e=S(c.streetAddress,Vb);R(f,e);var l="";if(c.city!=""){l=c.city;if(c.region!="")l+=", "}e=S(l,Wb);R(f,e);e=S(c.region,Xb);R(f,e)}e=S(c.country,Yb);R(f,e);
R(d,f);if(c.phoneNumbers&&c.phoneNumbers[y]){var p=b,u=b,x=c.phoneNumbers[0],z;for(var C=0;C<c.phoneNumbers[y];C++){z=c.phoneNumbers[C];if(z[La]=="main"){p=z;break}if(z[La]==""||z[La]=="mobile"&&u==b)u=z}z=p?p:u?u:x;e=S(z.number,Zb);R(d,e)}if(c.ddUrl&&c.ddUrl!=""){e=W(c.ddUrl,O.directions,this.s(),cc);R(d,e)}if(c.ddUrlToHere&&c.ddUrlToHere!=""&&c.ddUrlFromHere&&c.ddUrlFromHere!=""){e=T(dc);var G=S(O["get-directions"]+":",ec);e[w](G);G=W(c.ddUrlToHere,O["to-here"],this.s(),fc);e[w](G);G=S("-",Mb);
e[w](G);G=W(c.ddUrlFromHere,O["from-here"],this.s(),fc);e[w](G);R(d,e)}c.html=d;this.ma(c.html)};N(o[I].e[A],"createResultHtml",o[I].e[A].A);
o[I].e[A].qd=function(c){if(c.centerAndZoom){this.Ya=g;this.W=c;this.Z=b;this.V="";if(this.D)this.D=b}else if(c.setCenter){this.Ya=a;this.W=c;this.Z=b;this.Fa=b;this.V="";if(this.D)this.D=b}else if(c.x&&c.y){this.Ya=g;this.Z=c;this.Fa=b;this.W=b;this.V="";if(this.D)this.D=b}else if(c!=b&&c!=""){this.Ya=g;this.W=b;this.V=c;this.Z=b;if(this.D)this.D=b;var d=new o[I].e;d.bb(this,this.Nd,[d,c]);d[L](c)}};N(o[I].e[A],"setCenterPoint",o[I].e[A].qd);
o[I].e[A].Nd=function(c,d){if(c.results&&c.results[y]){var e={};e.y=da(c.results[0].lat);e.x=da(c.results[0].lng);this.Z=e;this.V=d;this.Ha=g;this.W=b;if(c.resultViewport){var f={};f.Cf=da(c.resultViewport.span.lat)/2;f.Df=da(c.resultViewport.span.lng)/2;this.Fa=f}}};
o[I].e[A].ia=function(c,d){if(d){if(this.D==b){var e=b;if(this.W==b){var f=T(Cd);this.D=ob(b,Gd,this.V==""?b:this.V);R(f,S(O["search-location"],Hd));R(f,this.D);R(c,f);e=this.D}f=T("gsc-configSetting");this.Ea=pb(b,"0",this.Sa,Ed);R(f,this.Ea);R(f,S(O["disable-address-lookup"],Fd));if(e==b)e=this.Ea;var j=S(b,"gsc-configSettingSubmit");R(j,nb(O[Ea],Dd));R(f,j);R(c,f);e[Ha]()}}else{if(this.D){if(this.D[za]){this.V=this.D[za];this.qd(this.V)}this.D=b}if(this.Ea){this.Sa=this.Ea[ua];this.Ea=b}ab(c)}};
o[I].e[A].Fe=function(c){if(c==o[I].e.ec)this.Sa=g;else if(c==o[I].e.fc)this.Sa=a};N(o[I].e[A],"setAddressLookupMode",o[I].e[A].Fe);o[I].e.nd=function(c,d,e,f){var j=c.staticMapUrl;j=j[F](/&h=\d*/,"&h="+d);j=j[F](/&w=\d*/,"&w="+e);if(f&&f>=o[I].e.Kc&&f<=o[I].e.Lc)j=j[F](/&zl=\d*/,"&zl="+f);c.staticMapUrl=j;return j};N(o[I].e,"resizeStaticMapUrl",o[I].e.nd);
o[I].e.Ud=function(c,d,e,f){var j="&Point=b&Point.latitude_e6=__LAT__&Point.longitude_e6=__LNG__&Point.iconid=__ICONID__&Point=e",i="",n="http://mt.google.com/mapdata?cc=us&tstyp=5&zl=4&w=150&h=100",l={};l.staticMapUrl=n;n=o[I].e.nd(l,d,e,f);if(f==b)n=n[F](/&zl=\d*/,"");var p=c[y];if(p>o[I].e.Eb)p=o[I].e.Eb;for(var u=0;u<p;u++){var x,z,C=c[u];if(C.lat&&C.lng)if(typeof C.lat=="string"){x=da(C.lat);z=da(C.lng)}else{x=C.lat;z=C.lng}else if(C.x&&C.y){x=C.y;z=C.x}else return b;var G=z*1000000,U=j[F](/__LAT__/,
r[xa](x*1000000));U=U[F](/__LNG__/,r[xa](G));var $=51+u;if(p==1)$=15;U=U[F](/__ICONID__/,$);i=i+U}return n+i};N(o[I].e,"computeStaticMapUrl",o[I].e.Ud);o[I].e[A].Q=function(c,d){if(c==o[I].a.gb)if(d){this.La=b;this.La=d==o[I].e.Rc||d==o[I].e.Uc||d==o[I].e.Vc?d:b}else this.La=b};N(o[I].e[A],"setRestriction",o[I].e[A].Q);o[I].m=function(){o[I].a[Fa](this);this.B="news";this.ua="/GnewsSearch";this.ga="http://news.google.com/nwshp";this.$f=b;this.Pa="site:";this.J=a;this.Ha=g;this.$=$a(this,this.ia);this.Ga="gsc-newsConfig";this.j=b;this.h=b};M("google.search.NewsSearch",o[I].m);Sa(o[I].m,o[I].a);o[I].m.z="GnewsSearch";N(o[I].m,"RESULT_CLASS",o[I].m.z);o[I].m.Bc="GnewsSearch.quote";N(o[I].m,"QUOTE_RESULT_CLASS",o[I].m.Bc);o[I].m.n=[];
o[I].m.G=function(c,d,e,f,j){var i=0;if(c)i=ca(c,10);var n=o[I].m.n[i];o[I].m.n[i]=b;n.O(d,e,f,j)};N(o[I].m,"RawCompletion",o[I].m.G);
o[I].m[A].aa=function(c,d,e,f){var j;j=e==b?o[I].a.ca(o[I].m.n,this):e;var i;i=d==b?"google.search.NewsSearch.RawCompletion":d;var n=this.ra(i,j,f);if(c||!c&&this.h){var l,p=b;if(c)p=c;if(this.F)p=p==b?this.F:p+" "+this.F;if(this.o)p=p==b?this.Pa+this.o:p+" "+this.Pa+this.o;l=p?"&q="+h(p):"";if(this.J)l=l+"&scoring=d";if(this.h){var u="";for(var x in this.h)if(x.charAt(0)==":")u+="&"+this.h[x];l=l+u}if(this.o&&this.Pa=="source:")n=n[F](/&hl=.*&/,"&hl=en&");n=n+l;this.t=l;if(f&&f!=0)this.t=this.t+
"&start="+f}return n};
o[I].m[A].A=function(c){c.html&&delete c.html;if(c.GsearchResultClass==o[I].m.Bc)return;var d=T(this.ba());X(d,Jb);var e;e=W(c.unescapedUrl,c[pa],this.s(),Nb);R(d,e);e=S(c.publisher,hc);R(d,e);var f=c[Aa][wa](",");if(f[y]>1){e=S(", "+f[f[y]-1],ic);R(d,e)}var j=new Date(c.publishedDate);e=S(" - "+this.Ja(j),vc);R(d,e);j=new Date(c.publishedDate);e=S(" - "+this.Pb(j),wc);R(d,e);e=S(c[ya],Ob);R(d,e);if(c.clusterUrl&&c.clusterUrl!=""){e=W(c.clusterUrl,O["related-articles"]+"&nbsp;&raquo;",this.s(),jc);
R(d,e)}c.html=d;this.ma(c.html)};N(o[I].m[A],"createResultHtml",o[I].m[A].A);o[I].m[A].Aa=function(c){if(c==b||c==""){this.o=b;this.Pa="site:"}else if(c[Ga]("[./:]")){this.Pa="site:";this.o=c}else{this.Pa="source:";this.o=c[F](/\s/g,"_")}};N(o[I].m[A],"setSiteRestriction",o[I].m[A].Aa);o[I].m[A].H=function(c){this.J=c==o[I].a.da?g:c==o[I].a.ea?a:a};N(o[I].m[A],"setResultOrder",o[I].m[A].H);
o[I].m[A].ia=function(c,d){if(d)if(this.j==b){var e=T(Cd);this.j=pb(b,"0",this.J,Ed);R(e,this.j);R(e,S(O["sort-by-date"],Fd));var f=T(Dd);R(f,nb(O[Ea],Dd));R(e,f);R(c,e);this.j[Ha]()}else{ha(this.j,this.J);this.j[Ha]()}else if(this.j)this.j[ua]?this.H(o[I].a.da):this.H(o[I].a.ea)};
o[I].m[A].Q=function(c,d){if(c==o[I].a.wb)if(d)for(var e in d){var f=d[e];if(e=="geo"){if(this.h==b)this.h={};this.h[":geo"]=e+"="+h(f)}if(e=="qsid"){if(this.h==b)this.h={};this.h[":qsid"]=e+"="+h(f)}if(e=="topic"){if(this.h==b)this.h={};this.h[":topic"]=e+"="+h(f)}if(e=="ned"){if(this.h==b)this.h={};this.h[":ned"]=e+"="+h(f)}if(e=="as_mind"){if(this.h==b)this.h={};this.h[":as_mind"]=e+"="+h(f)}if(e=="as_minm"){if(this.h==b)this.h={};this.h[":as_minm"]=e+"="+h(f)}if(e=="as_miny"){if(this.h==b)this.h=
{};this.h[":as_miny"]=e+"="+h(f)}if(e=="as_maxd"){if(this.h==b)this.h={};this.h[":as_maxd"]=e+"="+h(f)}if(e=="as_maxm"){if(this.h==b)this.h={};this.h[":as_maxm"]=e+"="+h(f)}if(e=="as_maxy"){if(this.h==b)this.h={};this.h[":as_maxy"]=e+"="+h(f)}}else this.h=b};N(o[I].m[A],"setRestriction",o[I].m[A].Q);o[I].i=function(){o[I].a[Fa](this);this.B="patent";this.ua="/GpatentSearch";this.ga="http://www.google.com/patents";this.vd="";this.$a=b;this.Ha=g;this.$=$a(this,this.ia);this.Ga="gsc-patentConfig";this.j=b};M("google.search.PatentSearch",o[I].i);Sa(o[I].i,o[I].a);o[I].i.z="GpatentSearch";N(o[I].i,"RESULT_CLASS",o[I].i.z);o[I].i.Pc=1;N(o[I].i,"TYPE_ANY_STATUS",o[I].i.Pc);o[I].i.Tc=2;N(o[I].i,"TYPE_ISSUED_PATENTS",o[I].i.Tc);o[I].i.Qc=3;N(o[I].i,"TYPE_APPLICATIONS",o[I].i.Qc);o[I].i.n=[];
o[I].i.G=function(c,d,e,f,j){var i=0;if(c)i=ca(c,10);var n=o[I].i.n[i];o[I].i.n[i]=b;n.O(d,e,f,j)};N(o[I].i,"RawCompletion",o[I].i.G);o[I].i[A].aa=function(c,d,e,f){var j;j=e==b?o[I].a.ca(o[I].i.n,this):e;var i;i=d==b?"google.search.PatentSearch.RawCompletion":d;var n=this.ra(i,j,f);if(c){var l,p=c;if(this.F)p=p+" "+this.F;l="&q="+h(p)+this.vd;if(this.$a)l=l+this.$a;n=n+l;this.t=l}return n};
o[I].i[A].A=function(c){c.html&&delete c.html;c.thumbnailHtml=this.Kb(c);var d=T(this.ba());X(d,Jb);var e=T(mc),f=eb(),j=fb(f,0),i=V(j,kc),n=V(j,mc);R(i,c.thumbnailHtml[Ka](g));R(n,e);R(d,f);var l;l=W(c.unescapedUrl,c[pa],this.s(),Nb);R(e,l);var p=T(xc+" "+nc);R(e,p);var u=b;u=c.patentNumber?c.patentStatus=="issued"?O["us-pat"]+"&nbsp;"+c.patentNumber:O["us-pat-app"]+"&nbsp;"+c.patentNumber:O["us-pat-app"]+"&nbsp; N/A";l=S(u,yc);R(p,l);if(c.applicationDate){l=S(" - "+this.Ja(new Date(c.applicationDate)),
vc);R(p,l)}if(c.assignee){l=S(" - "+c.assignee,gc);R(p,l)}l=S(c[ya],Ob);R(e,l);R(e,l);c.html=d;this.ma(c.html)};N(o[I].i[A],"createResultHtml",o[I].i[A].A);o[I].i[A].Kb=function(c){var d=T(zc),e=gb(c.tbUrl,75,100,sc),f=lb(c.unescapedUrl,b,this.s(),sc);Y(f,sc);R(f,e);R(d,f);return d};o[I].i[A].H=function(c){this.$a=c==o[I].a.da?"&scoring=d":c==o[I].a.Ac?"&scoring=ad":c==o[I].a.ea?b:b};N(o[I].i[A],"setResultOrder",o[I].i[A].H);
o[I].i[A].Q=function(c,d){if(c==o[I].a.gb)this.vd=d?d==o[I].i.Pc?"":d==o[I].i.Tc?"&as_psrg=1":d==o[I].i.Qc?"&as_psra=1":"":""};N(o[I].i[A],"setRestriction",o[I].i[A].Q);o[I].i[A].ia=function(c,d){if(d){var e=a;if(this.$a&&this.$a=="&scoring=d")e=g;if(this.j==b){var f=T(Cd);this.j=pb(b,"0",e,Ed);R(f,this.j);R(f,S(O["sort-by-date"],Fd));var j=T(Dd);R(j,nb(O[Ea],Dd));R(f,j);R(c,f);this.j[Ha]()}else{ha(this.j,e);this.j[Ha]()}}else if(this.j)this.j[ua]?this.H(o[I].a.da):this.H(o[I].a.ea)};o[I].w=function(){this.U=o[I].b.va;this.md=this.U;this.k=b;this.I={width:112,height:84};this.vb={width:100,height:75};this.Za=b};M("google.search.SearcherOptions",o[I].w);o[I].w[A].rd=function(c){switch(c){case o[I].b.kc:case o[I].b.Da:case o[I].b.va:this.U=c;break;default:this.U=o[I].b.va;break}this.md=this.U};N(o[I].w[A],"setExpandMode",o[I].w[A].rd);o[I].w[A].Me=function(c){ab(c);this.k=c};N(o[I].w[A],"setRoot",o[I].w[A].Me);o[I].w[A].qb=function(c){this.Za=c};
N(o[I].w[A],"setNoResultsString",o[I].w[A].qb);o[I].w[A].He=function(c){if(c>100)c=100;na(this.I,c);ga(this.I,r[ta](c*1.33))};N(o[I].w[A],"setImageResultsTbHeight",o[I].w[A].He);o[I].w[A].Se=function(c){if(c>100)c=100;na(this.vb,c);ga(this.vb,r[ta](c*1.33))};N(o[I].w[A],"setVideoResultsTbHeight",o[I].w[A].Se);o[I].S=function(){fa(this,b);this.ud=b;this.T=o[I].b.la};M("google.search.DrawOptions",o[I].S);o[I].S[A].Ie=function(c){fa(this,c)};N(o[I].S[A],"setInput",o[I].S[A].Ie);
o[I].S[A].Ne=function(c){this.ud=c};N(o[I].S[A],"setSearchFormRoot",o[I].S[A].Ne);o[I].S[A].Ge=function(c){this.T=c==o[I].b.la||c==o[I].b.Qa?c:o[I].b.la};N(o[I].S[A],"setDrawMode",o[I].S[A].Ge);
o[I].v=function(c,d,e){this.r=e;this.Nb=a;this.Ib=a;this.f=c;this.u=b;this.Be=Q(d,o[I].b[A].ve,[this]);this.Ee=Q(d,o[I].b[A].Wb,[this,o[I].v.Db]);this.De=Q(d,o[I].b[A].Wb,[this,o[I].v.Cb]);this.Ce=Q(d,o[I].b[A].Wb,[this,o[I].v.Jc]);this.Ae=Q(d,o[I].b[A].ue,[this]);this.ze=Q(d,o[I].b[A].qe,[this]);this.f.bb(d,o[I].b[A].O,[this]);this.f.ta(d.ob);this.f.ab(d.ya);this.k=b;this.tb=b;this.Wa=b;this.Yb=b;this.na=b;this.Ia=b;this.P=b;this.Xa=g};o[I].v.Bb=0;o[I].v.Db=1;o[I].v.Cb=2;o[I].v.Jc=3;
o[I].v[A].ac=function(c){var d=pd+" ";d+=c==o[I].v.Bb?this.r.U==o[I].b.va?qd:this.f.Ma==o[I].a.X?rd:sd:c==o[I].v.Db?qd:c==o[I].v.Cb?rd:sd;Y(this.Yb,d)};
o[I].b=function(c){if(!o[K].KeyVerified)if(o[I].b.kd())o[K].KeyVerified=g;else return;this.ob=o[I].a.X;this.T=o[I].b.la;this.k=b;this.pb=b;fa(this,b);this.sb=o[I].b.hb;this.le=Q(this,o[I].b[A].re,[b]);this.me=Q(this,o[I].b[A].se,[b]);this.nb=b;this.$b=b;this.Zb=b;this.Ka=b;this.oe=a;this.Ua=a;this.ya=o[I].a.Ra;this.Ub=O.copy;this.d=[];this.cf=[];var d;if(c)for(var e=0;e<c[y];e++){d=new o[I].v(c[e],this,a);this.d[oa](d)}};M("google.search.SearchControl",o[I].b);o[I].b.Id=O["no-results"];
N(o[I].b,"NO_RESULTS_DEFAULT_STRING",o[I].b.Id);o[I].b.Nc=350;N(o[I].b,"TIMEOUT_SHORT",o[I].b.Nc);o[I].b.hb=500;N(o[I].b,"TIMEOUT_MEDIUM",o[I].b.hb);o[I].b.Mc=700;N(o[I].b,"TIMEOUT_LONG",o[I].b.Mc);o[I].b.kc=1;N(o[I].b,"EXPAND_MODE_CLOSED",o[I].b.kc);o[I].b.Da=2;N(o[I].b,"EXPAND_MODE_OPEN",o[I].b.Da);o[I].b.va=3;N(o[I].b,"EXPAND_MODE_PARTIAL",o[I].b.va);o[I].b.la=1;N(o[I].b,"DRAW_MODE_LINEAR",o[I].b.la);o[I].b.Qa=2;N(o[I].b,"DRAW_MODE_TABBED",o[I].b.Qa);o[I].b.xc="save";
N(o[I].b,"KEEP_LABEL_SAVE",o[I].b.xc);o[I].b.wc="keep";N(o[I].b,"KEEP_LABEL_KEEP",o[I].b.wc);o[I].b.vc="include";N(o[I].b,"KEEP_LABEL_INCLUDE",o[I].b.vc);o[I].b.uc="copy";N(o[I].b,"KEEP_LABEL_COPY",o[I].b.uc);o[I].b.tc="blank";N(o[I].b,"KEEP_LABEL_BLANK",o[I].b.tc);try{o[I].b.appPath=m[Aa].href}catch(Md){o[I].b.appPath=b}
o[I].b.kd=function(){var c=g;if(wb(m[Aa].host))return g;if(o[K].LoadFailure)if(o[K].OriginalAppPath&&o[I].b.appPath)if(o[I].b.appPath==o[K].OriginalAppPath){o[K].LoadFailure=a;c=g}else{o[K].LoadFailure=a;c=g}o[K].KeyVerified=g;o[K].LoadFailure=a;return c};N(o[I].b,"keyCheck",o[I].b.kd);o[I].b[A].$d=function(c,d){if(!c)return;this.Ta=g;this.Zc=c;if(d){if(d.includeVerticalAds)this.fb=g;if(d.channel)this.Yc=d.channel}};N(o[I].b[A],"enableAds",o[I].b[A].$d);
o[I].b[A].Md=function(c,d){d||(d=new o[I].w);c.ja=b;this.d[oa](new o[I].v(c,this,d));if(Nd(c.B))this.je=g};N(o[I].b[A],"addSearcher",o[I].b[A].Md);
o[I].b[A].Yd=function(c,d){var e=b,f=b;if(d)if(d.T){this.T=d.T;e=d[D];f=d.ud}else this.T=o[I].b.la;else this.T=o[I].b.la;this.k=T(Ac);if(e!=b){fa(this,e);this[D].onkeyup=this.le;this[D].Pf=this.me}else{if(f==b)f=this.k;var j=new o[I].K(g,f);j.td(this,this.submit);j.sd(this,this.Gb);fa(this,j[D])}this.Na=T(Qc);if(this.T==o[I].b.Qa){this.R=T(ud);R(this.k,this.R);this.C=[];this.M=0;for(var i=0;i<this.d[y];i++){var n={},l=this.d[i].f.ie();l=l[F](/ /g,"&nbsp;");n.ha=S(l);n.qa=b;n.B=this.d[i].f.B;ka(n.ha,
Q(this,this.Ve,[i]));this.C[i]=n;R(this.R,n.ha);var p=Mb;if(Ua("opera"))p=p+" "+Mb+"-opera";var u=db(" ",p);R(this.R,u);this.d[i].r.rd(o[I].b.Da)}}this.ka=this.k;if(this.Ta){this.ka=T("gsc-wrapper");this.Y=T(Zc);this.fa=T(ad);R(this.ka,this.Y);R(this.k,this.fa);R(this.k,this.ka)}R(this.ka,this.Na);for(var i=0;i<this.d[y];i++){if(this.d[i].r.k){this.d[i].Xa=a;this.d[i].k=this.d[i].r.k;X(this.d[i].k,Mc);Z(this.d[i].k,Rc);X(this.d[i].k,Qc)}else this.d[i].k=T(Mc);this.d[i].f.db&&X(this.d[i].k,Mc+"-"+
this.d[i].f.db);if(this.T==o[I].b.Qa)this.C[i].qa=this.d[i].k;var x=eb(b,b,Pc),z=fb(x,0);this.d[i].Ca=V(z,dd);var C=V(z,ed);this.d[i].tb=S("",gd);R(this.d[i].Ca,this.d[i].tb);var G=S(this.d[i].f.ge(),jd);R(this.d[i].tb,G);this.d[i].Wa=S("",kd);R(this.d[i].Ca,this.d[i].Wa);var U=S(),$=S(O.blank,md),Da=S(O.blank,nd),la=S(O.blank,od);s($,O["show-one-result"]);s(Da,O["show-more-results"]);s(la,O["show-all-results"]);R(U,$);R(U,Da);R(U,la);ka($,this.d[i].Ee);ka(Da,this.d[i].De);ka(la,this.d[i].Ce);this.d[i].Yb=
U;this.d[i].ac(o[I].v.Bb);R(this.d[i].Ca,this.d[i].Yb);ka(this.d[i].tb,this.d[i].Be);if(this.d[i].f.$){this.d[i].L=db("",fd);cb(this.d[i].L,O.blank);X(this.d[i].L,hd);R(C,this.d[i].L);ka(this.d[i].L,this.d[i].Ae);s(this.d[i].L,O.settings);this.d[i].na=T(Bd);X(this.d[i].na,this.d[i].f.Ga);this.d[i].Ia=mb(Bd);X(this.d[i].Ia,this.d[i].f.Ga);this.d[i].Ia.onsubmit=this.d[i].ze;R(this.d[i].na,this.d[i].Ia);ma(this.d[i].na[H],"none")}this.d[i].P=T(Nc);X(this.d[i].P,this.d[i].f.dd());this.d[i].r.k==b&&R(this.Na,
this.d[i].k);R(this.d[i].k,x);this.d[i].na&&R(this.d[i].k,this.d[i].na);R(this.d[i].k,this.d[i].P)}if(this.T==o[I].b.Qa)for(var i=0;i<this.d[y];i++){X(this.C[i].ha,vd);X(this.C[i].qa,Ad);if(i==this.M){X(this.C[i].ha,wd);X(this.C[i].qa,yd)}else{X(this.C[i].ha,xd);X(this.C[i].qa,zd)}}if(c&&typeof c=="string")c=q.getElementById(c);if(c){bb(c,this.k);var Xa=this.ee();if(Xa&&Xa<300){this.oe=g;X(this.k,Bc)}}};N(o[I].b[A],"draw",o[I].b[A].Yd);
o[I].b[A].Pe=function(c){switch(c){case o[I].b.Nc:case o[I].b.hb:case o[I].b.Mc:this.sb=c;break;default:this.sb=o[I].b.hb;break}};N(o[I].b[A],"setTimeoutInterval",o[I].b[A].Pe);o[I].b[A].Ke=function(c,d,e){if(e)switch(e){case o[I].b.xc:case o[I].b.wc:case o[I].b.vc:case o[I].b.uc:case o[I].b.tc:this.Ub=O[e];break;default:this.Ub=e;break}this.nb=$a(c,d)};N(o[I].b[A],"setOnKeepCallback",o[I].b[A].Ke);function Nd(c){return c=="blog"||c=="image"?g:a}
o[I].b[A].Ve=function(c){if(this.M==c)return;Z(this.C[this.M].ha,wd);Z(this.C[this.M].qa,yd);X(this.C[this.M].ha,xd);X(this.C[this.M].qa,zd);this.M=c;X(this.C[this.M].ha,wd);X(this.C[this.M].qa,yd);Z(this.C[this.M].ha,xd);Z(this.C[this.M].qa,zd);if(this.Ta)Nd(this.C[this.M].B)?this.Qb():this.Xd()};o[I].b[A].Qb=function(){if(!this.Ta)return;Y(this.Y,Zc);Y(this.fa,ad);this.fb&&Z(this.ka,cd)};o[I].b[A].Xd=function(){if(!this.Ta)return;Y(this.Y,Yc);Y(this.fa,$c);this.fb&&X(this.ka,cd)};
o[I].b[A].submit=function(){this[D][za][y]?this[L]():this.Gb();return a};N(o[I].b[A],"submit",o[I].b[A].submit);
o[I].b[A].execute=function(c){var d;if(c){d=c;ia(this[D],d)}else d=this[D][za];if(d[y]){this.Ua=a;Y(this.Na,Rc);this.R&&Y(this.R,td);var e=this.Ta&&this.Zc;if(e&&this.je&&this.T==o[I].b.la)e=a;if(e){var f=this,j=this.ob==o[I].a.wa,i=j?"w2":"w1";if(this.fb)i=i+(j?"n4":"n2");m.google_afs_request_done=function(p){f.pe(p)};var n="http://www.google.com/search?output=js&num=0&q="+h(d)+"&client="+h(this.Zc)+"&ad="+h(i)+"&js=uds";if(this.Yc)n+="&channel="+h(this.Yc);Ya(n)}for(var l=0;l<this.d[y];l++){if(!this.d[l].Xa){Z(this.d[l].k,
Qc);X(this.d[l].k,Rc)}this.$b&&this.$b(this,this.d[l].f,d);if(this.d[l].f.ja)this.d[l].f.ja=b;this.d[l].f[L](d)}}};N(o[I].b[A],"execute",o[I].b[A][L]);
o[I].b[A].pe=function(c){m.google_afs_request_done=b;if(!this.Y)return;v(this.Y,"");v(this.fa,"");if(!c||c[y]<1){this.Qb();return}if(!this.R)for(var d=0;d<this.d[y];d++)if(Nd(this.d[d].f.B)){this.Qb();return}Y(this.Y,Yc);var e=a,f=q[J]("h2");v(f,O["ads-by-google"]);R(this.Y,f);var j=c[y];for(var d=0;d<j;d++){var i=c[d];if(i[La]=="text/wide"){var n=T(bd),l=W(i.url,i.line1,o[I].a.Ra);R(n,l);var p=q[J]("cite");v(p,i.visible_url);R(n,p);var u=db();v(u,i.line2);R(n,u);R(this.Y,n)}else if(this.fb){if(!e){e=
g;X(this.ka,cd);R(this.fa,f[Ka](g));Y(this.fa,$c)}var n=T(bd),l=W(i.url,i.line1,o[I].a.Ra);R(n,l);var u=db();v(u,i.line2+"<br/>"+i.line3);R(n,u);var p=q[J]("cite");v(p,i.visible_url);R(n,p);R(this.fa,n)}}this.fb&&!e&&Z(this.ka,cd)};o[I].b[A].re=function(){var c=this[D][za];if(c&&c!=""){this.Ka&&m[ra](this.Ka);this.Ka=m[va](Q(this,o[I].b[A][L],[b]),this.sb)}};o[I].b[A].se=function(){this.Ka&&m[ra](this.Ka);this.Ka=m[va](Q(this,o[I].b[A][L],[b]),this.sb)};
o[I].b[A].ta=function(c){switch(c){case o[I].a.wa:this.ob=c;break;default:case o[I].a.X:this.ob=o[I].a.X;break}for(var d=0;d<this.d[y];d++)this.d[d].f.ta(c)};N(o[I].b[A],"setResultSetSize",o[I].b[A].ta);o[I].b[A].ab=function(c){this.ya=c;for(var d=0;d<this.d[y];d++)this.d[d].f.ab(c)};N(o[I].b[A],"setLinkTarget",o[I].b[A].ab);o[I].b[A].qb=function(c){for(var d=0;d<this.d[y];d++)this.d[d].r.qb(c)};N(o[I].b[A],"setNoResultsString",o[I].b[A].qb);o[I].b[A].ve=function(c){c.Nb?this.Ba(c,a):this.Ba(c,g)};
o[I].b[A].Ba=function(c,d,e){if(d){Z(c.Ca,hd);X(c.Ca,id);c.Nb=g;ma(c.P[H],"block")}else{Z(c.Ca,id);X(c.Ca,hd);c.Nb=a;ma(c.P[H],"none");v(c.Wa,e?"(0)":"("+c.f.results[y]+")")}};o[I].b[A].qe=function(c){this.cb(c,a,g);return a};o[I].b[A].ue=function(c){if(c.f.Ha)c.Ib?this.cb(c,a,g):this.cb(c,g,g)};
o[I].b[A].cb=function(c,d,e){if(!d){if(c.L&&c.f.$){Z(c.L,id);X(c.L,hd);v(c.L,O.blank);c.Ib=a;c.f.$(c.Ia,a);ma(c.na[H],"none");e&&this[L]()}}else if(c.L&&c.f.$){X(c.L,id);Z(c.L,hd);v(c.L,O[Ea]);c.Ib=g;ma(c.na[H],"block");c.f.$(c.Ia,g)}};o[I].b[A].te=function(c,d){if(this.nb){d.f.ke();this.nb(c)}};o[I].b[A].Pd=function(){this.Ua=g};N(o[I].b[A],"cancelSearch",o[I].b[A].Pd);
o[I].b[A].Gb=function(){ia(this[D],"");Y(this.Na,Qc);this.R&&Y(this.R,ud);this.Y&&Y(this.Y,Zc);if(this.fa){Y(this.fa,ad);Z(this.ka,cd)}for(var c=0;c<this.d[y];c++){if(!this.d[c].Xa){Z(this.d[c].k,Rc);X(this.d[c].k,Qc)}var d=this.d[c];ab(d.P);d.u=b;this.Ba(d,a,g);this.cb(d,a,a)}};N(o[I].b[A],"clearAllResults",o[I].b[A].Gb);
o[I].b[A].O=function(c){var d,e,f=a,j;if(this.Ua)return;ab(c.P);c.u=b;this.Ba(c,a,g);this.cb(c,a,a);c.ac(o[I].v.Bb);var i=c.f.results;if(c.f.Va&&c.f.completionStatus>=400){i=[];i[oa](c.f.be())}else if(i[y]==0&&c.r.Za&&c.f.completionStatus==200){i=[];i[oa](c.f.ce(c.r.Za))}for(var e=0;e<i[y];e++){d=i[e];d.html||c.f.A(d);if(d.html){f=g;j=T(c.f.dd());X(j,Oc);c.f.db&&X(j,Oc+"-"+c.f.db);var n=d.html[Ka](g);if(d.GsearchResultClass==o[I].c.z){if(c.r.I)if(c.r.I[E]!=c.f.I[E]||c.r.I[Pa]!=c.f.I[Pa]){var l=n.getElementsByTagName("img");
for(var p=0;p<l[y];p++)o[I].a.Oa(d.tbWidth,d.tbHeight,c.r.I,l[p],g)}}else if(d.GsearchResultClass==o[I].q.z)if(c.r.vb){var l=n.getElementsByTagName("img");for(var p=0;p<l[y];p++)o[I].a.Oa(d.tbWidth,d.tbHeight,c.r.vb,l[p])}R(j,n);if(this.nb){var u=this.Ub,x=S("",ld);cb(x,u);R(j,x);ka(x,Q(this,o[I].b[A].te,[d,c]))}if(e>=c.f.ld){if(!c.u){c.u=T(Sc);R(c.P,c.u);if(c.r.U==o[I].b.va)ma(c.u[H],"none")}R(c.u,j)}else R(c.P,j)}}if(!c.u&&c.f[B]){c.u=T(Sc);R(c.P,c.u)}if(c.u&&c.f.t&&c.f.gwsUrl){j=W(c.f.gwsUrl,O["more-results"]+
"&nbsp;&raquo;",c.f.s(),Tc);if(c.f[B]){var z=T(Uc),C=this.Vd(c);z[w](C);z[w](j);R(c.u,z)}else R(c.u,j)}if(f){v(c.Wa,"("+c.f.results[y]+")");c.r.U==o[I].b.va||c.r.U==o[I].b.Da?this.Ba(c,g):this.Ba(c,a);var G=c.f.cd();G&&R(c.P,G)}else{v(c.Wa,"(0)");v(c.P,"");this.Ba(c,a)}c.r.U=c.r.md;this.Zb&&this.Zb(this,c.f)};N(o[I].b[A],"onSearchComplete",o[I].b[A].O);
o[I].b[A].Vd=function(c){var d=T(Vc),e=c.f[B];for(var f=0;f<e.pages[y];f++){var j=Wc;if(f==e.currentPageIndex)j=j+" "+Xc;var i=S(e.pages[f].label,j);ka(i,Q(this,o[I].b[A].ye,[c,f]));d[w](i)}return d};
o[I].b.Ic={border:"border",borderColor:"border-color",borderStyle:"border-style",borderWidth:"border-width",borderTop:"border-top",borderTopColor:"border-top-color",borderTopStyle:"border-top-style",borderTopWidth:"border-top-width",borderRight:"border-right",borderRightColor:"border-right-color",borderRightStyle:"border-right-style",borderRightWidth:"border-right-width",borderBottom:"border-bottom",borderBottomColor:"border-bottom-color",borderBottomStyle:"border-bottom-style",borderBottomWidth:"border-bottom-width",
borderLeft:"border-left",borderLeftColor:"border-left-color",borderLeftStyle:"border-left-style",borderLeftWidth:"border-left-width",color:"color",cssFloat:"float",styleFloat:"float",clear:"clear",cursor:"cursor",display:"display",font:"font",fontFamily:"font-family",fontSize:"font-size",fontStyle:"font-style",fontWeight:"font-weight",height:"height",margin:"margin",marginTop:"margin-top",marginRight:"margin-right",marginBottom:"margin-bottom",marginLeft:"margin-left",overflow:"overflow",padding:"padding",
paddingTop:"padding-top",paddingRight:"padding-right",paddingBottom:"padding-bottom",paddingLeft:"padding-left",textAlign:"text-align",textDecoration:"text-decoration",textTransform:"text-transform",verticalAlign:"vertical-align",visibility:"visibility",width:"width"};
o[I].b.hd=function(c,d){if(Za()){alert("google.search.SearchControl.inlineCurrentStyle is not supported on Safari");return}var e=g;if(d)e=d;if(e)for(var f=0;f<c.childNodes[y];f++)o[I].b.hd(c.childNodes[f],g);if(c.nodeType==1){var j,i,n=a,l=a;if(m[Ca]){j=m[Ca](c,b);i=g;n=g}else if(c[Ja]){j=c[Ja];i=a;n=g}if(n){for(var p in j)if(o[I].b.Ic[p]){var u=o[I].b.Ic[p],x=j[p];if(p=="display"&&x=="none"){v(c,"");l=g}if(j[p]!="")i?c[H].setProperty(u,x):c[H][Ia](u,x)}if(l)if(!i)c.outerHTML='<div style="display:none"/>'}}};
N(o[I].b,"inlineCurrentStyle",o[I].b.hd);o[I].b[A].ee=function(c){var d=c?c:this.k,e=b;if(m[Ca])e=m[Ca](d,b);else if(d[Ja])e=d[Ja];else if(q.defaultView[Ca])e=q.defaultView[Ca](d,b);return e?ca(e[E],10):300};o[I].b[A].bb=function(c,d){this.Zb=$a(c,d)};N(o[I].b[A],"setSearchCompleteCallback",o[I].b[A].bb);o[I].b[A].Oe=function(c,d){this.$b=$a(c,d)};N(o[I].b[A],"setSearchStartingCallback",o[I].b[A].Oe);
o[I].b[A].Wb=function(c,d){c.ac(d);var e=a;switch(d){default:case o[I].v.Db:if(c.u)ma(c.u[H],"none");break;case o[I].v.Cb:if(c.u)ma(c.u[H],"block");if(c.f.Ma!=o[I].a.X)e=g;c.f.ta(o[I].a.X);break;case o[I].v.Jc:if(c.u)ma(c.u[H],"block");if(c.f.Ma!=o[I].a.wa)e=g;c.f.ta(o[I].a.wa);break}if(e){var f;f=this[D][za];if(f[y]){this.Ua=a;Y(this.Na,Rc);this.R&&Y(this.R,td);if(!c.Xa){Z(c.k,Qc);X(c.k,Rc)}c.r.U=o[I].b.Da;c.f[L](f)}}};
o[I].b[A].ye=function(c,d){this.Ua=a;Y(this.Na,Rc);this.R&&Y(this.R,td);if(!c.Xa){Z(c.k,Qc);X(c.k,Rc)}c.r.U=o[I].b.Da;c.f.fd(d)};
o[I].K=function(c,d,e){var f=mb(Cc);f.acceptCharset="utf-8";var j=b,i=O["search-uc"],n=O[I];if(e){if(e.buttonText){i=e.buttonText;n=e.buttonText}if(e.clickableBrandingUrl){var l="http://www.google.com";if(typeof e.clickableBrandingUrl=="string"&&e.clickableBrandingUrl[Ga](/^http:\/\/[a-z]*\.google\.com/))l=e.clickableBrandingUrl;j=lb(l,b,"_BLANK");t(j,Kc)}}this.pb=nb(i,Dc);s(this.pb,n);var p;if(c){p=Hc;this.Hb=S(O.blank,Ec);s(this.Hb,O["clear-results"])}else p=Jc;fa(this,ob(b,Fc,b));this[D].name=
"search";s(this[D],n);var u=eb(b,b,Cc);R(f,u);var x=fb(u,0);this.jd=V(x,Fc);var z=V(x,Dc);if(c){var C=V(x,Ec);R(C,this.Hb)}R(this.jd,this[D]);R(z,this.pb);var G=eb(b,b,Gc);R(f,G);x=fb(G,0);this.userDefinedCell=V(x,Ic);var U=V(x,Lc),$=V(x,p),Da=S(O["powered-by"],Lc),la=kb(o[K][Na]+"/css/small-logo.png",51,15,p);R(U,Da);if(j){R(j,la);R($,j)}else R($,la);this.pd=f;ab(d);R(d,this.pd)};M("google.search.SearchForm",o[I].K);
o[I].K[A].td=function(c,d){this.wd=Q(this,this.Ue,[this]);this.rb=Q(c,d,[this]);this.pd.onsubmit=this.wd;ka(this.pb,this.wd)};N(o[I].K[A],"setOnSubmitCallback",o[I].K[A].td);o[I].K[A].sd=function(c,d){ka(this.Hb,Q(c,d,[this]))};N(o[I].K[A],"setOnClearCallback",o[I].K[A].sd);o[I].K[A].Ue=function(){var c=this.jd.offsetWidth,d=this[D][za];this.rb&&this.rb();if(Ua("msie")){var e=this,f;f=d[y]*8>=c?c-6:"99%";m[va](function(){ga(e[D][H],f)},1)}return a};
o[I].K[A].execute=function(c){if(c)ia(this[D],c);this.rb&&this.rb()};N(o[I].K[A],"execute",o[I].K[A][L]);o[I].q=function(){o[I].a[Fa](this);this.B="video";this.ua="/GvideoSearch";this.ga="http://video.google.com/videosearch";this.J=a;this.Ha=g;this.$=$a(this,this.ia);this.Ga="gsc-videoConfig";this.j=b};M("google.search.VideoSearch",o[I].q);Sa(o[I].q,o[I].a);o[I].q.z="GvideoSearch";N(o[I].q,"RESULT_CLASS",o[I].q.z);o[I].q.n=[];o[I].q.G=function(c,d,e,f,j){var i=0;if(c)i=ca(c,10);var n=o[I].q.n[i];o[I].q.n[i]=b;n.O(d,e,f,j)};N(o[I].q,"RawCompletion",o[I].q.G);
o[I].q[A].aa=function(c,d,e,f){var j;j=e==b?o[I].a.ca(o[I].q.n,this):e;var i;i=d==b?"google.search.VideoSearch.RawCompletion":d;var n=this.ra(i,j,f);if(c){var l,p=c;if(this.F)p=p+" "+this.F;l="&q="+h(p);if(this.J)l=l+"&scoring=d";n=n+l;this.t=l;if(f&&f!=0)this.t=this.t+"&start="+f}return n};
o[I].q[A].A=function(c){c.html&&delete c.html;var d=T(this.ba());X(d,Jb);var e=T(kc),f=T(mc),j=eb(),i=fb(j,0),n=V(i,kc),l=V(i,mc);R(n,e);R(l,f);R(d,j);var p=o[I].a.Oa(c.tbWidth,c.tbHeight,this.I),u=gb(c.tbUrl,p[E],p[Pa],sc),x=lb(c.url,b,this.s(),sc);Y(x,sc);R(x,u);R(e,x);var z;z=W(c.url,c[pa],this.s(),Nb);R(f,z);var C=S(c[ya],Ob);if(Ua("msie"))na(C[H],"2.6em");R(f,C);z=S(this.Ja(new Date(c.published)),vc);R(f,z);z=W("http://"+c.publisher,c.publisher,this.s(),hc);R(f,z);c.html=d;this.ma(c.html)};
N(o[I].q[A],"createResultHtml",o[I].q[A].A);o[I].q.Wd=function(c,d){var e=b;if(c.playUrl&&c.playUrl!=""){var f=c.playUrl,j=Jd;if(d)j=d;if(Ua("opera")){var i=q[J]("object");t(i,j);i[Ia]("type","application/x-shockwave-flash");i[Ia]("data",f);e=T(d);e[w](i)}else{var i=q[J]("embed");t(i,j);i[Ia]("type","application/x-shockwave-flash");i[Ia]("src",f);if(c.videoType)c.videoType=="Google"?i[Ia]("bgcolor","#000000"):i[Ia]("wmode","transparent");else i[Ia]("bgcolor","#000000");e=T(d);e[w](i)}}return e};
N(o[I].q,"createPlayer",o[I].q.Wd);o[I].q[A].H=function(c){this.J=c==o[I].a.da?g:c==o[I].a.ea?a:a};N(o[I].q[A],"setResultOrder",o[I].q[A].H);o[I].q[A].ia=function(c,d){if(d)if(this.j==b){var e=T(Cd);this.j=pb(b,"0",this.J,Ed);R(e,this.j);R(e,S(O["sort-by-date"],Fd));var f=T(Dd);R(f,nb(O[Ea],Dd));R(e,f);R(c,e);this.j[Ha]()}else{ha(this.j,this.J);this.j[Ha]()}else if(this.j)this.j[ua]?this.H(o[I].a.da):this.H(o[I].a.ea)};o[I].g=function(){o[I].a[Fa](this);this.B="web";this.ua="/GwebSearch";this.ga="http://www.google.com/search";this.o=b;this.N=o[I].g.pa;this.xa=b;this.Mb=b;this.oa=b;this.za=b;this.h=b};M("google.search.WebSearch",o[I].g);Sa(o[I].g,o[I].a);o[I].g.z="GwebSearch";N(o[I].g,"RESULT_CLASS",o[I].g.z);o[I].g.kb="cx";N(o[I].g,"cxRestriction_CX",o[I].g.kb);o[I].g.jb="cref";N(o[I].g,"cxRestriction_CREF",o[I].g.jb);o[I].g.pa="none";N(o[I].g,"cxRestriction_NONE",o[I].g.pa);o[I].g.n=[];
o[I].g.G=function(c,d,e,f,j){var i=0;if(c)i=ca(c,10);var n=o[I].g.n[i];o[I].g.n[i]=b;n.O(d,e,f,j)};N(o[I].g,"RawCompletion",o[I].g.G);
o[I].g[A].aa=function(c,d,e,f){var j;j=e==b?o[I].a.ca(o[I].g.n,this):e;var i;i=d==b?"google.search.WebSearch.RawCompletion":d;var n=this.ra(i,j,f);if(c){var l,p=c;if(this.F)p=p+" "+this.F;if(this.o&&this.N!=o[I].g.pa&&this.Mb){var u=this.Mb,x=p;if(this.xa!=b)x=p+" more:"+this.xa;u=u[F](/__HL__/,o[I][Oa]);u=u[F](/__QUERY__/,h(x));this.oa=u}if(this.o&&this.N==o[I].g.pa)p=p+" site:"+this.o;l="";if(this.o&&this.N!=o[I].g.pa){if(this.N==o[I].g.kb)l=l+"&cx="+this.o;else if(this.N==o[I].g.jb)l=l+"&cref="+
h(this.o);if(this.xa!=b)p=p+" more:"+this.xa}l=l+"&q="+h(p);if(this.za)l=l+"&safe="+this.za;if(this.h)l=l+this.h;n=n+l;this.t=l;if(f&&f!=0)this.t=this.t+"&start="+f}return n};o[I].g[A].A=function(c){c.html&&delete c.html;var d=T(this.ba());X(d,Jb);var e;e=W(c.unescapedUrl,c[pa],this.s(),Nb);R(d,e);e=S(c[ya],Ob);R(d,e);e=S(c.visibleUrl,Pb);R(d,e);X(e,Rb);var f=c.unescapedUrl[Ba](c.visibleUrl),j=c.visibleUrl;if(f!=-1&&f!=0)j=c.unescapedUrl.substring(f);e=S(j,Pb);X(e,Qb);R(d,e);c.html=d;this.ma(c.html)};
N(o[I].g[A],"createResultHtml",o[I].g[A].A);
o[I].g[A].Aa=function(c,d,e){this.oa=b;this.Va=b;var f=a;if(c==b||typeof c=="string"&&c==""){f=a;this.o=b;this.N=o[I].g.pa;this.xa=b;this.Va=b}else if(typeof c=="string"){f=c[Ga](/^\d{21}:.*/);if(f){this.o=c;this.N=o[I].g.kb}else{this.o=c;this.N=o[I].g.pa}}else if(c.siteUrl){f=a;this.o=c.siteUrl}else if(c.cseId){f=g;this.o=c.cseId;this.N=o[I].g.kb}else if(c.crefUrl){f=g;this.o=c.crefUrl;this.N=o[I].g.jb;this.Va=O["linked-cse-error-results"]}else{f=a;this.o=b;this.N=o[I].g.pa;this.xa=b}if(f){if(d)this.xa=
d;if(e)if(e[Ga](/__HL__/)&&e[Ga](/__QUERY__/))this.Mb=e;if(this.N==o[I].g.jb)(new Image).src="http://www.google.com/cse/tools/ping?cref="+h(this.o)+"&nocache="+Number(new Date)}};N(o[I].g[A],"setSiteRestriction",o[I].g[A].Aa);o[I].g[A].Q=function(c,d){if(c==o[I].a.xb)this.za=d?d==o[I].a.Ab||d==o[I].a.zb||d==o[I].a.yb?d:b:b;if(c==o[I].a.wb)if(d)for(var e in d){var f=d[e];if(e=="lr"||e=="usg"){if(this.h==b)this.h="&";else this.h+="&";this.h+=e+"="+h(f)}}else this.h=b};N(o[I].g[A],"setRestriction",o[I].g[A].Q);if(!o[I].NoOldNames){k("GwebSearch",o[I].g);k("GbookSearch",o[I].l);k("GblogSearch",o[I].p);k("GvideoSearch",o[I].q);k("GnewsSearch",o[I].m);k("GlocalSearch",o[I].e);k("GimageSearch",o[I].c);k("GpatentSearch",o[I].i);k("GSearch",o[I].a);k("GSearchControl",o[I].b);k("GSearchForm",o[I].K);k("GsearcherOptions",o[I].w);k("GdrawOptions",o[I].S)};
google.loader.loaded({"module":"search","version":"1.0","components":["default"]});
google.loader.eval.search = function() {eval(arguments[0])}})()